<?php

namespace Database\Seeders;

use App\Enums\RoleEnum;
use App\Models\User;
use App\Services\UserRoleService;
use DB;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Schema;

class UserSeeder extends Seeder
{
    public function __construct(
        private readonly UserRoleService $service
    ) {
    }

    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        DB::table('users')->truncate();

        $users = [
            [
                'id' => '1',
                'first_name' => 'Admin',
                'last_name' => 'Admin',
                'email' => 'admin@gcccibadan.org',
                'phone_number' => '08164650987',
                'gender' => 'Male',
                'address' => null,
                'community' => null,

                'status' => null,
                'email_verified_at' => null,
                'password' => '',
                'remember_token' => null,
                'date_of_birth' => null,
                'date_of_visit' => null,
                'created_at' => '31-08-25 1:02',
                'updated_at' => '31-08-25 1:02',
            ],
            [
                'id' => '75',
                'first_name' => 'Opeyemi',
                'last_name' => 'Okunola',
                'email' => 'opeyemiadebowale1759@gmail.com',
                'phone_number' => '08146412563',
                'gender' => 'Male',
                'address' => null,
                'community' => null,

                'status' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$xz7x3sqbZjimj5K6kRQx3.5zQclaQLJYLVbsFqCeQpwv139zSGK2S',
                'remember_token' => null,
                'date_of_birth' => null,
                'date_of_visit' => null,
                'created_at' => '31-08-25 1:02',
                'updated_at' => '31-08-25 1:02',
            ],
            [
                'id' => '2',
                'first_name' => 'Samuel',
                'last_name' => 'Abiodun',
                'email' => 'abiodundigitalhub@gmail.com',
                'phone_number' => '08164650987',
                'gender' => 'Male',
                'address' => null,
                'community' => null,

                'status' => null,
                'email_verified_at' => null,
                'password' => '',
                'remember_token' => null,
                'date_of_birth' => null,
                'date_of_visit' => null,
                'created_at' => '31-08-25 1:02',
                'updated_at' => '31-08-25 1:02',
            ],
             [
                'id' => '98',
                'first_name' => 'Abiodun',
                'last_name' => 'Samuel Oluyemi',
                'email' => 'abiodunsamyemi@gmail.com',
                'phone_number' => '08164650987',
                'gender' => 'Male',
                'address' => null,
                'community' => null,


                'status' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$bN89yfg1TV.MhZIkrFgyMuI9NGIt3UdB6UuObj1MNpaFyysy7u5Y6',
                'remember_token' => null,
                'date_of_birth' => null,
                'date_of_visit' => null,
                'created_at' => '31-08-25 1:02',
                'updated_at' => '31-08-25 1:02',
            ],
            // [
            //     'id' => '3',
            //     'first_name' => 'Oluwatobi',
            //     'last_name' => 'Abiona',
            //     'email' => 'Oluwatobiabiona2@gmail.com',
            //     'phone_number' => '08132432908',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$6uxkt/4ftjOTvRnlHLDTMe4zkD0jP8Mg7ERAapa4Yk3DLuO1lDRKG',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '4',
            //     'first_name' => 'Rosemary',
            //     'last_name' => 'Achebe',
            //     'email' => 'rosemaryashebe@gmail.com',
            //     'phone_number' => '08133215849',
            //     'gender' => 'Female',
            //     'address' => 'Ore Oloruntofunmi hostel, Major Salawu, Agbowo',
            //     'community' => null,
            //
            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$utI.fHP28kyPZQa1L6MoFu4.s5t8M80D4.z9xfm7Ipi8aQ5ji6L.y',
            //     'remember_token' => null,
            //     'date_of_birth' => '20-Jul',
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '5',
            //     'first_name' => 'Peter',
            //     'last_name' => 'Adeagbo',
            //     'email' => 'adeagbooluwagboyegapeter95@gmail.com',
            //     'phone_number' => '08142658150',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$3UI48HDrFkCRaj.O3bOvr.rQcexyymRvUJnQCFET7O.JcNdWIotRi',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '6',
            //     'first_name' => 'John',
            //     'last_name' => 'Adeagbo',
            //     'email' => 'adeagbojohnluj@gmail.com',
            //     'phone_number' => '09153835134',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$F6k5zTYph91.X1IVaPPAIe5TIGelJN0x/nBnTbd8koUW2KU61oTwW',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '7',
            //     'first_name' => 'Ajibade',
            //     'last_name' => 'Adedayo',
            //     'email' => 'theewhy72@gmail.com',
            //     'phone_number' => '09068979739',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$fq8P1SkAHdOZXFDMKL32tOLWqJ1UrHqhKnqfUsfmFd0ejduHzYgOW',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '8',
            //     'first_name' => 'Adeuyi',
            //     'last_name' => 'Adejoke',
            //     'email' => 'Adejokeadeuyi0@gmail.com',
            //     'phone_number' => '07032913692',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$6aAWIFIQvWlosvCxL5i.g.5PgSgyvoCDNmpN6QifBqljY8w8NElEy',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '9',
            //     'first_name' => 'James',
            //     'last_name' => 'Adeleke',
            //     'email' => 'adejames97@gmail.com',
            //     'phone_number' => '08080392216',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$WAKn87wRXVlSejN/L1UXrOhhMfxztm1SbDROSMCf2dHGgTxEDoAO2',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '10',
            //     'first_name' => 'Adebisi',
            //     'last_name' => 'Ademusire',
            //     'email' => 'aadebisijoe@gmail.com',
            //     'phone_number' => '07031123695',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$cL6pQVpdgfJTPVj8Je0XBeDrzYMbC/gilPyYkJZyK0VqSFmhRx2Ym',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '11',
            //     'first_name' => 'Yetunde',
            //     'last_name' => 'Adeniyi',
            //     'email' => 'ayowealth4real@gmail.com',
            //     'phone_number' => '09168373724',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$ff0EMLhQpYT3GbZujPtZIuzUbnFQ.hzNoQ8dl.v7AT1ERn2E6rysS',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '12',
            //     'first_name' => 'Victoria',
            //     'last_name' => 'Adesoji',
            //     'email' => 'Victoriaadesoji@gmail.com',
            //     'phone_number' => '08127925156',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$OA6/o3x.S5KyxNlm.pHsFe2KfQuuvki9cdWRFJ7tlvMdp670x03he',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '13',
            //     'first_name' => 'Oluwatimileyin',
            //     'last_name' => 'Adewale',
            //     'email' => 'adewaleoluwatimileyin2020@gmail.com',
            //     'phone_number' => '07061631763',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$APjQqphl3QZYpGtOfE7KAupGqD1S8CNEpgmIj28t9hw7Yd2.VgRN2',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '14',
            //     'first_name' => 'Samuel',
            //     'last_name' => 'Adeyemo',
            //     'email' => 'adexpsalm2@gmail.com',
            //     'phone_number' => '08145996831',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$HuAxh8C795U7YKTUD91dvueb4a13GLUPz8gvaExVg6BIVPt5AllGW',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '15',
            //     'first_name' => 'Adeyemi',
            //     'last_name' => 'Agoro',
            //     'email' => 'agoroadeyemi65@gmail.com',
            //     'phone_number' => '08148989175',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$njy6O94DKmYVgYopY8wZduGhiSivyaqdUuG09CGXj55MzKDBSuA6y',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '16',
            //     'first_name' => 'Opeyemi',
            //     'last_name' => 'Ajala',
            //     'email' => 'eesuolaopeyemi7@gmail.com',
            //     'phone_number' => '08162000203',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$9JDeBF2g4MjqUDKKoxuFC.3QLKnuEG71Zb42KqY0xtTwTh9tHnalS',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '17',
            //     'first_name' => 'Oluwasegun',
            //     'last_name' => 'Ajala',
            //     'email' => 'james.ajala@yahoo.com',
            //     'phone_number' => '07065518839',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$3JjqOTV5BxUB8a8BtrLPbO45oSr35BKLnCDf.2xyvuR86ktmXuGom',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '18',
            //     'first_name' => 'Tolulope',
            //     'last_name' => 'Ajikanle',
            //     'email' => 'ajikanletajworth@gmail.com',
            //     'phone_number' => '07068727719',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$yT6g/4EUxB/5qmU/Lk2zA./7tRloLiVbH5NBeyzkcVkptbQ3t4Qnq',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '19',
            //     'first_name' => 'Abayomi',
            //     'last_name' => 'Akande',
            //     'email' => 'akandeaaj@gmail.com',
            //     'phone_number' => '08132402786',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$GpjTQdsfAWO234mnASy9VOtFS3UCEMoBkSZXw9pDXhITOPoGytCLi',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '20',
            //     'first_name' => 'Christopher',
            //     'last_name' => 'Akinfenwa',
            //     'email' => 'taiwoakinfenwa2019@gmail.com',
            //     'phone_number' => '07049546094',
            //     'gender' => 'Male',
            //     'address' => 'UI',
            //     'community' => null,
            //
            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$ZQlBY0zSPow4TWv7zxwcI.cEbyK1Udj0GQstTMplVsHsDjTocLs5m',
            //     'remember_token' => null,
            //     'date_of_birth' => '10-Aug',
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '21',
            //     'first_name' => 'Toluwalashe',
            //     'last_name' => 'Akinola',
            //     'email' => 'akinolatoluwalashe48@gmail.com',
            //     'phone_number' => '08102810733',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$kH2CKdSBKLtA4rhEFtTCCOCZMDtqNXvkRxv5/nO7.Fxi3LkyDMVZG',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '22',
            //     'first_name' => 'Oluwadamilola',
            //     'last_name' => 'Alabi',
            //     'email' => 'alabidamilola0507@gmail.com',
            //     'phone_number' => '08138236051',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$NqMprmWskKZz4oo8AgOBS.QyTWgE1llH/qmVMRGL9v5bLB9GWZTne',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '23',
            //     'first_name' => 'Marvel',
            //     'last_name' => 'Angulu',
            //     'email' => 'angulumarvel@gmail.com',
            //     'phone_number' => '08053388869',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$ipWFFUTHDxAwEyB4wuqFNOu39WwnQaaKKFlhHw.1rB8VxMfGxU/gq',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '25',
            //     'first_name' => 'Jesunifesimi',
            //     'last_name' => 'Ayedona',
            //     'email' => 'grace789nife@gmail.com',
            //     'phone_number' => '08121569780',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$4BSrcKDSmygSKGPzLnvUBO72ValdTDW83x9qC2bVB5rTnlTMxCZQq',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '26',
            //     'first_name' => 'Praise',
            //     'last_name' => 'Ayoade',
            //     'email' => 'Bigpraise001@gmail.com',
            //     'phone_number' => '09070959365',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$WwcChYzCXHwcx2w1xKu8rumXOg.i5gd4v2ib1tnQfrkFA8te1by1y',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '27',
            //     'first_name' => 'Taiwo',
            //     'last_name' => 'Bajomo',
            //     'email' => 'rotimibajomo32@gmail.com',
            //     'phone_number' => '07048578260',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$in00eyaYi/xco8h.kAsPquVIEbqrczHUKATIUqtisHN.4wuUzKmye',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '28',
            //     'first_name' => 'Paul',
            //     'last_name' => 'Bamibe',
            //     'email' => 'bamibepaul@gmail.com',
            //     'phone_number' => '08137971612',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$f2J1bmA5f3pN1iu6BTaMWOV5ZK.L5dDGJewCcQg353avQes0fVF5m',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '29',
            //     'first_name' => 'Erioluwa',
            //     'last_name' => 'Bamibe',
            //     'email' => 'erioluwabamibe@gmail.com',
            //     'phone_number' => '09039598060',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$DEx6KdtYfKGa/2khQasayO/N2ghZ6L8UeGt23i71ueIhFig0Q4pae',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '30',
            //     'first_name' => 'Esther',
            //     'last_name' => 'Benson',
            //     'email' => 'bensone797@gmail.com',
            //     'phone_number' => '09061848780',
            //     'gender' => 'Female',
            //     'address' => 'Sawmill, Old Ife road, Ibadan',
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$UdKUPg3eFYMXzjA0WEVWWuRNy.uOdN9v5gSY.GE5Y2TK.D4vhARQ2',
            //     'remember_token' => null,
            //     'date_of_birth' => '01-Jan',
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '31',
            //     'first_name' => 'Honor-Jesus',
            //     'last_name' => 'Bezaleel',
            //     'email' => 'bhonourjesus@gmail.com',
            //     'phone_number' => '09033344206',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$fcxDLnLNoEPpji3BgqZ70uRId3cLSBAoZpvLCCjO1OsZmhZibq/AO',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '32',
            //     'first_name' => 'Abigael',
            //     'last_name' => 'Blessing',
            //     'email' => 'abigaelblessing2021@gmail.com',
            //     'phone_number' => '07087502990',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$DQFQYQwWqnz730c87o.S.uuGhXW93pVHW.urQWQYz0sNO4GELlR1m',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '33',
            //     'first_name' => 'Abiodun',
            //     'last_name' => 'Chikodi',
            //     'email' => 'Akintayokemi626@gmail.com',
            //     'phone_number' => '09153881831',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$RjPLK8sFxzYE30rhssKVJenedEYB6Dn2/DR7yir0GUabwh9wcGkAq',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '34',
            //     'first_name' => 'Oluwatobiloba',
            //     'last_name' => 'Dairo',
            //     'email' => 'gladysoluwatobi@gmail.com',
            //     'phone_number' => '08180203799',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$CJY.hiElXHJect1QodWiq.5XuNiu7BAEHPszrRKxYEa8AJpe1upFK',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '35',
            //     'first_name' => 'Agbaraoluwa',
            //     'last_name' => 'David',
            //     'email' => 'davidagbaraoluwa19@gmail.com',
            //     'phone_number' => '07032512720',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //
            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$qiJEIqj0Ii61s4C.ioraQuKlI3hOaZRolk44Dm0urN0ED3XeVPacy',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '36',
            //     'first_name' => 'Benjamin',
            //     'last_name' => 'Ekinns',
            //     'email' => 'inihobongbenjamin@gmail.com',
            //     'phone_number' => '09122315574',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$PeNks4uzDN9Fr1vegwl2T.YNCT/TFpeMh9wR/qNkxE3VMYyF5NWp2',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '37',
            //     'first_name' => 'Jessica',
            //     'last_name' => 'Emmanuel',
            //     'email' => 'jessicaemmanuel039@gmail.com',
            //     'phone_number' => '09022644851',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$rH0ndJZjIGxZT..PyFQOx.Lpu5C3O8DFNqfs.9qF6by5RE4cYgM3a',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '38',
            //     'first_name' => 'Ayomide',
            //     'last_name' => 'Emmanuel',
            //     'email' => 'emmanayomide1@gmail.com',
            //     'phone_number' => '07069947801',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$RNAKSUxcOl/uk6hBx5WkEOlWJeAMxRVryawFsLmnZdx2SLE6.k/hK',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '39',
            //     'first_name' => 'Amudipe',
            //     'last_name' => 'Esther',
            //     'email' => 'Xtarife3@gmail.com',
            //     'phone_number' => '08147192513',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$XTUnigt61TMD/003zrScPeu3wA5mjab4qSd/FUPqFqDdWYbGr69SW',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '40',
            //     'first_name' => 'Comfort',
            //     'last_name' => 'Fadiya',
            //     'email' => 'comfortfadiya@gmail.com',
            //     'phone_number' => '07031686396',
            //     'gender' => 'Female',
            //     'address' => 'Bodija, Ibadan',
            //     'community' => null,
            //
            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$8/XHJ22yvlIcWk9OR6ghFexsnxGKEpNOKZHBwkW4wBVnIGiRj2aoG',
            //     'remember_token' => null,
            //     'date_of_birth' => '23-Sep',
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '41',
            //     'first_name' => 'Ayomide',
            //     'last_name' => 'Fasasi',
            //     'email' => 'AyomideFasasi@gmail.com',
            //     'phone_number' => 'Ayomide',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //
            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$T6zqqMyu8u3EiNiGYAyHtOALJfxQ2Eu4HmDzzl9R/TJ6DySBlPa3y',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '42',
            //     'first_name' => 'Salami',
            //     'last_name' => 'Feyisara',
            //     'email' => 'feyisharahdolapo@gmail.com',
            //     'phone_number' => '08113045029',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$3tLcXUdpsNzD8CneM/Bo4.UEBTCqHcxpDywDzBARJBDRQ5Vjv339y',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '43',
            //     'first_name' => 'Olamide',
            //     'last_name' => 'Gbadegesin',
            //     'email' => 'gbadeola2010@gmail.com',
            //     'phone_number' => '09027919322',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$B2wJxlxFCc5JI1hytRAofeHf9S.zEtnHuD8EqUj9uZmzRamXlzd2e',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '44',
            //     'first_name' => 'Olasunkanmi',
            //     'last_name' => 'Gbadegesin',
            //     'email' => 'olasunkanmi.gbadegesin@gmail.com',
            //     'phone_number' => '09063474054',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$khpSf/iPwYUjbHTTCOCtQ.6VQJCzxweXJnoy/uRqU5gYb8EjfArcK',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '45',
            //     'first_name' => 'Oluwalayomi',
            //     'last_name' => 'Gbadegesin',
            //     'email' => 'oluwalayomifunmilola@gmail.com',
            //     'phone_number' => '08104398529',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$H1qfwuuKW96QDdNJtKT/zedQExRsNrowhDN3h7OiPQ.qAP9q5DrTm',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '46',
            //     'first_name' => 'Comfort',
            //     'last_name' => 'Godwin',
            //     'email' => 'godwincomfort14@gmail.com',
            //     'phone_number' => '09127758876',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$j3kSsh0pfAt0wEX4N.MOKe/nc22/.x3DkHhX6OZy1uoGV6J214Fu.',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '47',
            //     'first_name' => 'Faith',
            //     'last_name' => 'Igwe',
            //     'email' => 'patienceigwe.7facebook@gmail.com',
            //     'phone_number' => '09167129850',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$yYNiEUQJeBj14SsvtVhwc.2nHuxJfpsucnfq333XrAwgc6npKVJtS',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '48',
            //     'first_name' => 'Chisom',
            //     'last_name' => 'Igwe',
            //     'email' => 'Kimberlyigwe@gmail.com',
            //     'phone_number' => '08083176669',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$R6dEX5jQD13Zi/1/gwoGz.gBonvctj/Y6fEn5NRrlLB3NUxyZabAe',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '49',
            //     'first_name' => 'Blessing',
            //     'last_name' => 'Iloduba',
            //     'email' => 'ogechi.chiqito@gmail.com',
            //     'phone_number' => '08135762874',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$kw6EO5aqnOxkGMQ6akmpk.dBmFmht4yAS/F2yFArgYWNVo8YzVIQ2',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '50',
            //     'first_name' => 'Oyindamola',
            //     'last_name' => 'Ishola',
            //     'email' => 'isholaoyindamola93@gmail.com',
            //     'phone_number' => '07069293698',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$I9K338ieb0Bp4m3WSSzZo.DsLMiZ84NrinTA7Y7ts.40ejPYaa2cq',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '52',
            //     'first_name' => 'Adebayo',
            //     'last_name' => 'Joseph',
            //     'email' => 'adebayophilipjoseph@gmail.com',
            //     'phone_number' => '08101761075',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$V8J0/t8izaiehnGeqnlKvufgM685JwivP7cDMlF0G/tZrL5yWuLr6',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '53',
            //     'first_name' => 'Funmilayo',
            //     'last_name' => 'Joseph',
            //     'email' => 'Funmilayormodara@gmail.com',
            //     'phone_number' => '07031005595',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$2mw4aooxPrKivrOECrDPQ.GosJPtYNo30u02s.stKG8Owd/xwbwYi',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '54',
            //     'first_name' => 'Emmanuel',
            //     'last_name' => 'King',
            //     'email' => 'Emmanuelolatayo54@gmail.com',
            //     'phone_number' => '07038644539',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$TbsD7m/8fBxCl68Q7bscLeRgqBMtVEV9LWZOXjxusywsNnyoAunH.',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '55',
            //     'first_name' => 'Tomike',
            //     'last_name' => 'Kolajo',
            //     'email' => 'kolajoelizabeth@gmail.com',
            //     'phone_number' => '08106827158',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$2hpOS21vr4xMXVKl1JgTHe3XKQ7tTCMAVgNISS87u/mmsLWRyImmO',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '56',
            //     'first_name' => 'Ademola Pelumi',
            //     'last_name' => 'Lawal',
            //     'email' => 'pelumiademola260@gmail.com',
            //     'phone_number' => '08167257148',
            //     'gender' => 'Male',
            //     'address' => 'Foye Street, Adegbayi',
            //     'community' => null,
            //
            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$xAcqfcsDzOhuPbiT9JiL/.eckt0NWXl5M1ZN5xCkqEnjxL0H01ecC',
            //     'remember_token' => null,
            //     'date_of_birth' => '14-Jan',
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '57',
            //     'first_name' => 'Morireoluwa',
            //     'last_name' => 'Lawrence',
            //     'email' => 'morireoluwalawrence@gmail.com',
            //     'phone_number' => '09019963839',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$ew4GwKcUfGSMeNYo0bdKXOjNWn9nhXtVpl.ChWsuo9HRlk3EoMYN6',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '58',
            //     'first_name' => 'Layo',
            //     'last_name' => 'Mi',
            //     'email' => 'empresslayomi@gmail.com',
            //     'phone_number' => '08161245884',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$NuDCdXgtBcFk//e4EMaiSeD2Du7G3VIR6d.EExSJ0nWB1INt3nDRC',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '59',
            //     'first_name' => 'Daniel',
            //     'last_name' => 'Micah-Daniels',
            //     'email' => 'lekanm715@gmail.com',
            //     'phone_number' => '08134754954',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$3RXAF9ASjbPYCF/y1G0KO.CfWIRXKB2u7WCF/4YpmbE0SG7tnmvDm',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '60',
            //     'first_name' => 'Olajumoke',
            //     'last_name' => 'Michael',
            //     'email' => 'michaelolajumoke98@gmail.com',
            //     'phone_number' => '08163071708',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$EfRtUWH/nPtqiwMYqEaOMeDdEUPV0pgC6jbDPkbvZoPW/MSrNprUG',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '61',
            //     'first_name' => 'Kehinde',
            //     'last_name' => 'Moronfolu',
            //     'email' => 'oluwatomisinsarah@gmail.com',
            //     'phone_number' => '07037618943',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$kTnZ/dpABPnBRpucFcuuSeWvcOdCah.L3BrbKdKADNFSumx/VsfK2',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '63',
            //     'first_name' => 'Adejumo',
            //     'last_name' => 'Mosunmola',
            //     'email' => 'Mosunmlaadejumo50@mail.com',
            //     'phone_number' => '08102355043',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$zo9AT6hqvxb02kSPbMQsMemaBbG.fOBC81OlbXdqbT6GEKDwwJ9Hi',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '64',
            //     'first_name' => 'Sanmi-alao',
            //     'last_name' => 'Moyosoreoluwa',
            //     'email' => 'tmoyosoreoluwa@gmail.com',
            //     'phone_number' => '08073505634',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$IVsDOdUon65t0RZPE.xa3eNlVpZjSqbFvSH9E3OcF4sxRki9OgTEC',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '65',
            //     'first_name' => 'Yisau',
            //     'last_name' => 'Mujidat oluwafunmilayo',
            //     'email' => 'Avow16@gmail.com',
            //     'phone_number' => '08164263035',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$OiczQ3yBp34fxW4J5GOIq.qDguO4lO2YHOH0mS0i2m6mbeF3BoCyO',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '66',
            //     'first_name' => 'Ike',
            //     'last_name' => 'Niyi',
            //     'email' => 'Niyiike@gmail.com',
            //     'phone_number' => '08143500722',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$yxOKqrL4W.GdUuPCw8FSCuCpREaQSxfRfbTAeL6n2lfKc4Lcqmvnq',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '67',
            //     'first_name' => 'Jane',
            //     'last_name' => 'Nwaiwu',
            //     'email' => 'jhanedhera@gmail.com',
            //     'phone_number' => '09030553734',
            //     'gender' => 'Female',
            //     'address' => 'Agbowo, Ibadan',
            //     'community' => null,
            //
            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$X3.7v7OuBiYIt6usMIUJSusTNoF35/WlE/FUt4owYJB/MwAx.ajZS',
            //     'remember_token' => null,
            //     'date_of_birth' => '11-May',
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '68',
            //     'first_name' => 'Oluwaremilekun',
            //     'last_name' => 'Ogunnowo',
            //     'email' => 'ogunnowooluwaremilekun7@gmail.com',
            //     'phone_number' => '08164338510',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$F6z2FeZzOCLC4XHNVZ0CxeQ89ga6ilcjsKg9AfrhL.SRZPIjGhe.6',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '70',
            //     'first_name' => 'Timilehin',
            //     'last_name' => 'Oguntuase',
            //     'email' => 'raphaelbts232@gmail.com',
            //     'phone_number' => '07037464638',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$1BOQRUtKZk73X4TwigzFZ.uZafggHY4ptd63xOgNI0ccv7jUsf7eW',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '71',
            //     'first_name' => 'Taiwo',
            //     'last_name' => 'Ojeleye',
            //     'email' => 'Ojeleyetaiwo00@gmail.com',
            //     'phone_number' => '09075816455',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$pLV7yVMfj3jNqp7ZJJ60qubCHMC/euBroRjIMNWowABREV.mYdVmq',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '72',
            //     'first_name' => 'Jane',
            //     'last_name' => 'Ojewole',
            //     'email' => 'Ololadetaiwoj@gmail.com',
            //     'phone_number' => '09034499599',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$hLU7EOsqtfUcGkSdW8SXLeUz/y4scWLOb7gwBezrn41P/ZOw.FwZq',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '73',
            //     'first_name' => 'Tolani',
            //     'last_name' => 'Ojo',
            //     'email' => 'ojotolanimercy2019@gmail.com',
            //     'phone_number' => '08164100979',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$sc6qPaSQzn4bY6CXuxPXY.GRv61T2Vhr14qQCniiHTGSYJP1TVFZa',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '74',
            //     'first_name' => 'Victor',
            //     'last_name' => 'Okonkwo',
            //     'email' => 'Okonkwovictordgreat@gmail.com',
            //     'phone_number' => '09129138514',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$cLRl2vLH.mePPvVU5Kw.7uXPkBZ8whg9vPZiHP4QzuUCS1Egnv3Da',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],

            // [
            //     'id' => '76',
            //     'first_name' => 'Israel',
            //     'last_name' => 'Olajide',
            //     'email' => 'olajideisreal2000@gmail.com',
            //     'phone_number' => '07048781604',
            //     'gender' => 'Male',
            //     'address' => 'Independence hall, UI',
            //     'community' => null,
            //
            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$nz560Uka0FfvtoEOLK9Nl.bUeUWbbEyW2xz4EDALlio5/MF6YYeCq',
            //     'remember_token' => null,
            //     'date_of_birth' => '02-Jul',
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '78',
            //     'first_name' => 'Opeyemi',
            //     'last_name' => 'Olanase',
            //     'email' => 'olanaseopeyemi069@gmail.com',
            //     'phone_number' => '08108448464',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$5jZWCs6cOjQFHxaazFyGk.007eUz1ATtbeOpGqPwMiXfYSfMNrQ76',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '80',
            //     'first_name' => 'Inioluwa',
            //     'last_name' => 'Olarinoye',
            //     'email' => 'blessingolarinoye1@gmail.com',
            //     'phone_number' => '08138867668',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$jzREEjc21ds1mMwChaAzuukJpAe0vg9BlH3ZsdHmXQMtfFvacCUZG',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '81',
            //     'first_name' => 'Oluwaseun',
            //     'last_name' => 'Olatunde',
            //     'email' => 'oluwaseunolatundeaj@gmail.com',
            //     'phone_number' => '08062739882',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$W0MvXnzgUifvjDFnh3f9mOaCS9urpG6GrM5.Qe4D6UYSlads5ZguK',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '82',
            //     'first_name' => 'Favour',
            //     'last_name' => 'Olatunji',
            //     'email' => 'favourolatunji1505@gmail.com',
            //     'phone_number' => '09073877048',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$xJc5T8j.bneVcyI2IWij/OB1BqUBye7uy2FLT1cPlA3hy2khat//a',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '83',
            //     'first_name' => 'Inioluwa',
            //     'last_name' => 'Olatunji',
            //     'email' => 'olatunjiinioluwa2308@gamil.com',
            //     'phone_number' => '08037316709',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$IAIU29.Yz6baswdp4/EZe.mhke/rcX9RoSjdv5Ae9f7ZCFVa2DnKm',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '84',
            //     'first_name' => 'Favour',
            //     'last_name' => 'Olujimi',
            //     'email' => 'Olujinmifavoureniiyi@gmail.com',
            //     'phone_number' => '08167231700',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$ESQGY7nSf/mBNAEMKKU6..ODuHOggakhFfJbVpuIZ922mzF9YPQNa',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '85',
            //     'first_name' => 'Joseph',
            //     'last_name' => 'Olusi',
            //     'email' => 'olusijoseph23@gmail.com',
            //     'phone_number' => '09023809732',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$OvcKjjF8.8TMAlT/pIsqlOrau01K2PtgL0ucLFZz3tSQwULaeF3M6',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '86',
            //     'first_name' => 'Oluwanishola',
            //     'last_name' => 'Oluwalowo',
            //     'email' => 'oluwanisholaoluwalowo@gmail.com',
            //     'phone_number' => '08166041582',
            //     'gender' => 'Male',
            //     'address' => '16 Flats, Agbowo, Ibadan',
            //     'community' => null,
            //
            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$GqeODGlaPb7GhRdSfZdBOOv3B3.fAeO7D/iwHybOsFSw2BxRyzUky',
            //     'remember_token' => null,
            //     'date_of_birth' => '09-May',
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '87',
            //     'first_name' => 'ADELEKE',
            //     'last_name' => 'OLUWATOMISIN',
            //     'email' => 'holuwartominsin@gmail.com',
            //     'phone_number' => '08142452114',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$c85n6qoz/KHw8HcziZkKq.f.SqvrtC20eQOm/yUSzw3Inx8akfcSa',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '88',
            //     'first_name' => 'Oluwatoni',
            //     'last_name' => 'Omotosho',
            //     'email' => 'loisyforlife@gmail.com',
            //     'phone_number' => '08097478687',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$UhuyZLWN3qA3n5xbZxad6uNsHlwOGB7mISh46c0N5neaVBFVfnCq2',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '89',
            //     'first_name' => 'Oluwadara',
            //     'last_name' => 'Onakomaiya',
            //     'email' => 'oluwadaraeyitayo@gmail.com',
            //     'phone_number' => '07084173610',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$KQVQTVPxSlJ74NwNAgip2u5WwcKFogetQ1Na8DUT0pTZ5tqq/1ZKy',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '90',
            //     'first_name' => 'Oluwagbemisola',
            //     'last_name' => 'Oni',
            //     'email' => 'Gbemisolaoni09@gmail.com',
            //     'phone_number' => '09160851717',
            //     'gender' => 'Female',
            //     'address' => 'Akala Estate, Akobo, Ibadan',
            //     'community' => null,
            //
            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$Rg2shVo6qgX5yyRyKna8COzQB1JXrGkRc2IV8nGd4lt2gxagIkpY6',
            //     'remember_token' => null,
            //     'date_of_birth' => '03-Sep',
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '93',
            //     'first_name' => 'Anita',
            //     'last_name' => 'Patrick',
            //     'email' => 'anitaeleguase@gmail.com',
            //     'phone_number' => '08142762104',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$rbzf.fh/dygRcaQlSBuvQeKKaZV9OKp09iIvxudIoapOj5Zq9qs9u',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '95',
            //     'first_name' => 'Surprise',
            //     'last_name' => 'Popoola',
            //     'email' => 'popesurprise@gmail.com',
            //     'phone_number' => '09038834820',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$DJsRaUTqmNhLnd5ZCW5XxOeTHU45nM9vyRsA9/ZAQS6F7cfyXDNRK',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '96',
            //     'first_name' => 'Olamide',
            //     'last_name' => 'Rolake',
            //     'email' => 'Olofinkoyamorolake@gmail.com',
            //     'phone_number' => '08142628163',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$04TKGBD8lEFN8aiPZaSgPu.n2xvmnlpabjEdOhiiGKvi1oU0fZ4T.',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '97',
            //     'first_name' => 'Pelumi',
            //     'last_name' => 'Samson',
            //     'email' => 'samsongold001@gmail.com',
            //     'phone_number' => '09030841037',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$f9ZaoXVgrLmHHxhM6zOIKOg10n9Ff38.V2D7rrN1fBCm7J4bOplRi',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],

            // [
            //     'id' => '99',
            //     'first_name' => 'Oluwapelumi',
            //     'last_name' => 'Sodeinde',
            //     'email' => 'Pemzysodes@gmail',
            //     'phone_number' => '07076643023',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$gtrSmBuk32GvzcuJpq.9HOYUH5/mluXoKDL8caixeHCkRzJvIgF0y',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '100',
            //     'first_name' => 'Olalekan',
            //     'last_name' => 'Sonubi',
            //     'email' => 'sonubilekansolomon@gmail.com',
            //     'phone_number' => '07052546083',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$dqjD/0q2wd0wzm7YSjflI.4AwpnbOsNYOidy1qfWT8bNzdaOrLuMq',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '101',
            //     'first_name' => 'Kofoworola Daphne',
            //     'last_name' => 'Soyinka',
            //     'email' => 'daphnesoyinka7@gmail.com',
            //     'phone_number' => '09025637257',
            //     'gender' => 'Female',
            //     'address' => 'Akala Estate, Akobo, Ibadan',
            //     'community' => null,
            //
            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$8uIEam7VH8kwXs34gGKmXeuiiuQYiScj3Akl.L8zp8qJeNKx9Z.DS',
            //     'remember_token' => null,
            //     'date_of_birth' => '14-Jul',
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '102',
            //     'first_name' => 'Gospel',
            //     'last_name' => 'Sunday',
            //     'email' => 'gospelojonugwasunday@gmail.com',
            //     'phone_number' => '07044606099',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$V8c3fG.68qFzHia7DIiK4uFUg8ZE2wHANuw3VptoufRQnEgD0Xpzy',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '103',
            //     'first_name' => 'Jesulayomi',
            //     'last_name' => 'Taiwo',
            //     'email' => 'taiwojesulayomi95@gmail.com',
            //     'phone_number' => '08084074360',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$RwkI8K7AnJxRUUDXMee6pucQnXsOaXxNNDdfbW0vhfnJkdQzEQhZq',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '104',
            //     'first_name' => 'Jesujoba',
            //     'last_name' => 'Taiwo',
            //     'email' => 'jesujobataiwo@gmail.com',
            //     'phone_number' => '07061225747',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$Ey7tgW38vwiNjRTZ/MEHp.7Zx1F6VYZQgNmRH8WaK/IKgHd2Mkrf.',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '105',
            //     'first_name' => 'Jesunitemi',
            //     'last_name' => 'Taiwo',
            //     'email' => 'rhemataiwo@gmail.com',
            //     'phone_number' => '08063737737',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$p0oDUQLkLIE.CURVWAfn3.BP581yI58aRI7WP8MkDk/78hD.MWdye',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '106',
            //     'first_name' => 'Ayomikun',
            //     'last_name' => 'Taiwo',
            //     'email' => 'ayomikun010@gmail.com',
            //     'phone_number' => '08168259465',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$I76khcVXZ5A1Y.U6ElR0kenTGcnv.EeYc8zKpTT5IhEZ1lgucpvXS',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '107',
            //     'first_name' => 'Damilola',
            //     'last_name' => 'Tayo',
            //     'email' => 'damilolamariam70@gmail.com',
            //     'phone_number' => '09068924237',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$vCE87qMNTCexCSBN.NB4GeW4J6Pp5p7JnDY4F5ZEUSf8zR0tlREOK',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '108',
            //     'first_name' => 'Opayemi',
            //     'last_name' => 'Teniola Victoria',
            //     'email' => 'Opayemiteniola@gmail.com',
            //     'phone_number' => '08130409112',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$VhUf6QR6Bg8XSxew32pP0e8B5vZ9knOg2R/LwzUGFYYlebQREF1U2',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '109',
            //     'first_name' => 'Miracle',
            //     'last_name' => 'Ugochukwu',
            //     'email' => 'miracleugochukwu216@gmail.com',
            //     'phone_number' => '08124716614',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => 'Distant due the NYSC',
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$qBTeQf5rEHtuJswdpLUlQ.dFiz.z8rt6yrS3ptOxdhlxvZ5.M0vCi',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '110',
            //     'first_name' => 'Oluwagbenga',
            //     'last_name' => 'Victor',
            //     'email' => 'olabodevictor28@gmail.com',
            //     'phone_number' => '08107936667',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$g41rexgOgp5OmyYr63h2n.UX5zKbhZRcUkBINrhHloZPMm8tIIA76',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 1:02',
            //     'updated_at' => '31-08-25 1:02',
            // ],
            // [
            //     'id' => '113',
            //     'first_name' => 'DORCAS',
            //     'last_name' => 'toyin',
            //     'email' => 'dorcasfakayode19@gmail.com',
            //     'phone_number' => '07032146606',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$PIMIcaBdBzRLHOFgjUamie7wCwOROxpF5auTlc0WZyv3L71C6jrTm',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '31-08-25 12:57',
            //     'updated_at' => '31-08-25 12:57',
            // ],
            // [
            //     'id' => '114',
            //     'first_name' => 'Oluwatoyin Faith',
            //     'last_name' => 'Peter',
            //     'email' => 'oluwatoyinfaith26@gmail.com',
            //     'phone_number' => '08114857637',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$UYflxhuFfs5/kLZfpeAAfubH6xKhqew3uUQkmx0IFfxDIsOPyO7si',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '01-09-25 3:53',
            //     'updated_at' => '01-09-25 3:53',
            // ],
            // [
            //     'id' => '115',
            //     'first_name' => 'Victory',
            //     'last_name' => 'Abalaka',
            //     'email' => 'abalakassec@gmail.com',
            //     'phone_number' => '09037788489',
            //     'gender' => null,
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$DBlVR9YoyZlWNgMmQzLMNOlAfYrjY8RuJMJA/3UZHSblFT3N0.Fuu',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '01-09-25 5:03',
            //     'updated_at' => '01-09-25 5:03',
            // ],
            // [
            //     'id' => '116',
            //     'first_name' => 'Oluwagbemiga',
            //     'last_name' => 'Flourish',
            //     'email' => 'flourisholuwagbemiga2019@gmail.com',
            //     'phone_number' => '07038575845',
            //     'gender' => null,
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$9DKQep.fJjGrVzaUucH1rOuVntRLSGXw/iR8xdTmPaPfpv7X2X8T6',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '01-09-25 5:03',
            //     'updated_at' => '01-09-25 5:03',
            // ],
            // [
            //     'id' => '117',
            //     'first_name' => 'Success',
            //     'last_name' => 'Udu',
            //     'email' => 'udusuccess18@gmail.com',
            //     'phone_number' => '07054947265',
            //     'gender' => null,
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$ao3EK.D86w5U4YKrZpgVmOD9FoTEqUs.pRMMHIuOgs8WR8VaQyGhi',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '01-09-25 5:03',
            //     'updated_at' => '01-09-25 5:03',
            // ],
            // [
            //     'id' => '118',
            //     'first_name' => 'Oluwatobiloba',
            //     'last_name' => 'Bello',
            //     'email' => 'bellotobiloba40@gmail.com',
            //     'phone_number' => '08128479329',
            //     'gender' => null,
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$bcCJjUDp3SjJJ7fLP4snmelNS3vNbbc.C7SQIvYkr8wyx2arwqcpG',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '01-09-25 5:03',
            //     'updated_at' => '01-09-25 5:03',
            // ],
            // [
            //     'id' => '119',
            //     'first_name' => 'Susan',
            //     'last_name' => 'Uweribeno',
            //     'email' => 'susanayobami3@gmail.com',
            //     'phone_number' => '09121339005',
            //     'gender' => null,
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$/VYnYaQtEEoj8o9K9hNQz.ewx05E7CK0MlopYUpsQWgF8BFj2I.D6',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '01-09-25 5:03',
            //     'updated_at' => '01-09-25 5:03',
            // ],
            // [
            //     'id' => '120',
            //     'first_name' => 'Isaiah',
            //     'last_name' => 'Olaoye',
            //     'email' => 'olaisaiah54@gmail.com',
            //     'phone_number' => '08057661190',
            //     'gender' => null,
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$l3RCYI0n2qVyRweHbbxTNur5UuhIuPk3fZZ05X.9l28V.M4wGDO7C',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '01-09-25 5:03',
            //     'updated_at' => '01-09-25 5:03',
            // ],
            // [
            //     'id' => '121',
            //     'first_name' => 'Goodness',
            //     'last_name' => 'Udofia',
            //     'email' => 'goodnesseffiong1811@gmail.com',
            //     'phone_number' => '08102113246',
            //     'gender' => null,
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$YWdo5J22T/CrLsixqvmLwePsVEDTkWDZjtEyV18d67yI9MnGS576y',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '01-09-25 5:03',
            //     'updated_at' => '01-09-25 5:03',
            // ],
            // [
            //     'id' => '122',
            //     'first_name' => 'Kemi',
            //     'last_name' => 'Kemi',
            //     'email' => 'osakuadeoluwakemisola@gmail.com',
            //     'phone_number' => '09051388493',
            //     'gender' => null,
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$lyAP9s7/X5Ylq.PfFLv.wewbvPLfKo6xNiAA8XmjZa0ToHwLUoJGm',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '01-09-25 5:03',
            //     'updated_at' => '01-09-25 5:03',
            // ],
            // [
            //     'id' => '123',
            //     'first_name' => 'Gift',
            //     'last_name' => 'Akpala',
            //     'email' => 'akpalagift24@gmail.com',
            //     'phone_number' => '08064776696',
            //     'gender' => null,
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$M3l8druNlm2L7NpLuD8oAOpeiDEBpmqydXuZhhaTh97y2x7AtrrcO',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '01-09-25 5:03',
            //     'updated_at' => '01-09-25 5:03',
            // ],
            // [
            //     'id' => '124',
            //     'first_name' => 'Bukola',
            //     'last_name' => 'Olanase',
            //     'email' => 'Bukolaolanase1000@gmail.com',
            //     'phone_number' => '07017965065',
            //     'gender' => null,
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$HF2OatNCGgn.6emJ/Ao/S.qw7piNOVLo6CEkZX5KZhpZKbPLkyIly',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '01-09-25 5:03',
            //     'updated_at' => '01-09-25 5:03',
            // ],
            // [
            //     'id' => '126',
            //     'first_name' => 'Temitayo',
            //     'last_name' => 'ojo',
            //     'email' => 'tayot1556@gmail.com',
            //     'phone_number' => '07047344329',
            //     'gender' => 'Male',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$WiTDjmVsaIwcokrdvF7etOMzL2a3WPMNmlbwRE4/sccLDc4Tjvauu',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '10-09-25 4:58',
            //     'updated_at' => '10-09-25 4:58',
            // ],
            // [
            //     'id' => '127',
            //     'first_name' => 'victoria',
            //     'last_name' => 'oluwapelumi',
            //     'email' => 'victoriaoluwapelumi6@mail.com',
            //     'phone_number' => '07043029108',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$GbNYXqpNsY6TWemVCOBfUO66un8T/3e6G8bJRpMEkL.ZF9KqiE8Yq',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '10-09-25 5:16',
            //     'updated_at' => '10-09-25 5:16',
            // ],
            // [
            //     'id' => '128',
            //     'first_name' => 'Arewa',
            //     'last_name' => 'Ajisafe',
            //     'email' => 'arewaoluwa60@gmail.com',
            //     'phone_number' => '09064060072',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$KWJSbrzDPHIVYXh1FBLFoukmqcSbZHeC/kT7pQCvWyd/IbYxQqE92',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '22-09-25 22:10',
            //     'updated_at' => '22-09-25 22:10',
            // ],
            // [
            //     'id' => '129',
            //     'first_name' => 'Oluwatobiloba',
            //     'last_name' => 'Oyedokun',
            //     'email' => 'oyedokunoluwatobiloba@gmail.com',
            //     'phone_number' => '0807395670',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$sglnywfrvLsNfQgClpAfg.3i6hT0ucAVnF4.zZViDLULqM9cPfK1y',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '22-09-25 22:14',
            //     'updated_at' => '22-09-25 22:14',
            // ],
            // [
            //     'id' => '130',
            //     'first_name' => 'Esther',
            //     'last_name' => 'Bolaji Ikeoluwa',
            //     'email' => 'BolajiIkeoluwa5@gmail.com',
            //     'phone_number' => '09025153468',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //

            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$7MA.keW9JKLqH15LlNjUzeFHyWHnnCC.qLD1N9gz2ah1Iazgmm9Wm',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '22-09-25 22:20',
            //     'updated_at' => '22-09-25 22:20',
            // ],
            // [
            //     'id' => '131',
            //     'first_name' => 'opeyemi',
            //     'last_name' => 'balogun',
            //     'email' => 'Ibkbalogun18@gmail.com',
            //     'phone_number' => '09164789369',
            //     'gender' => 'Female',
            //     'address' => null,
            //     'community' => null,
            //
            //     'status' => null,
            //     'email_verified_at' => null,
            //     'password' => '$2y$12$AulD/uptrslXafIZyQN60ORLQthyYhlYuBKUG9mWXPf1HLW6nfioG',
            //     'remember_token' => null,
            //     'date_of_birth' => null,
            //     'date_of_visit' => null,
            //     'created_at' => '28-09-25 8:03',
            //     'updated_at' => '28-09-25 8:03',
            // ],
        ];

        foreach ($users as $userData) {
            $userData['password'] = Hash::make($userData['phone_number']);
            $userData['created_at'] = now();
            $userData['updated_at'] = now();
            $userData['status'] = 'active';
            $userData['date_of_visit'] = null;

            $user = User::create($userData); //
            if ($userData['email'] == 'admin@gcccibadan.org'  || $userData['email'] == 'Opeyemiadebowale1759@gmail.com') {
                $this->service->assignUserRoles($user, [
                    RoleEnum::ADMIN->value,
                    RoleEnum::LEADER->value,
                    RoleEnum::MEMBER->value,
                ]);
            } else if($userData['email'] == 'abiodunsamyemi@gmail.com'){
                $this->service->assignUserRoles($user, [
                    RoleEnum::LEADER->value,
                ]);
            }else{
                 $this->service->assignUserRoles($user, [
                    RoleEnum::MEMBER->value,
                ]);
            }
        }

        Schema::enableForeignKeyConstraints();
    }
}
