<?php

namespace Database\Seeders;

use App\Enums\UserRole;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $users = [
            [
                "email" => "string@gmail.com",
                "first_name" => "User",
                "last_name" => "User",
                "phone_number" => "string",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "email" => "string2@gmail.com",
                "first_name" => "User 2",
                "last_name" => "User 2",
                "phone_number" => "string2",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oluwatobi",
                "last_name" => "Abiona",
                "phone_number" => 8132432908,
                "email" => "Oluwatobiabiona2@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Rosemary",
                "last_name" => "Achebe",
                "phone_number" => 8133215849,
                "email" => "rosemaryashebe@gmail.com",
                "gender" => "Female",
                "address" => "Ore Oloruntofunmi hostel, Major Salawu, Agbowo",
                "date_of_birth" => "20-Jul",
                "community" => "",
                "worker" => "Yes",
                "unit" => "Worship Team",
                "status" => ""
            ],
            [
                "first_name" => "Peter",
                "last_name" => "Adeagbo",
                "phone_number" => 8142658150,
                "email" => "adeagbooluwagboyegapeter95@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "John",
                "last_name" => "Adeagbo",
                "phone_number" => 9153835134,
                "email" => "adeagbojohnluj@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Ajibade",
                "last_name" => "Adedayo",
                "phone_number" => 9068979739,
                "email" => "theewhy72@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Adeuyi",
                "last_name" => "Adejoke",
                "phone_number" => 7032913692,
                "email" => "Adejokeadeuyi0@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "James",
                "last_name" => "Adeleke",
                "phone_number" => 8080392216,
                "email" => "adejames97@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Adebisi",
                "last_name" => "Ademusire",
                "phone_number" => 7031123695,
                "email" => "aadebisijoe@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Yetunde",
                "last_name" => "Adeniyi",
                "phone_number" => 9168373724,
                "email" => "ayowealth4real@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Victoria",
                "last_name" => "Adesoji",
                "phone_number" => 8127925156,
                "email" => "Victoriaadesoji@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oluwatimileyin",
                "last_name" => "Adewale",
                "phone_number" => 7061631763,
                "email" => "adewaleoluwatimileyin2020@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Samuel",
                "last_name" => "Adeyemo",
                "phone_number" => 8145996831,
                "email" => "adexpsalm2@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Adeyemi",
                "last_name" => "Agoro",
                "phone_number" => 8148989175,
                "email" => "agoroadeyemi65@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Opeyemi",
                "last_name" => "Ajala",
                "phone_number" => 8162000203,
                "email" => "eesuolaopeyemi7@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oluwasegun",
                "last_name" => "Ajala",
                "phone_number" => 7065518839,
                "email" => "james.ajala@yahoo.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Tolulope",
                "last_name" => "Ajikanle",
                "phone_number" => 7068727719,
                "email" => "ajikanletajworth@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Abayomi",
                "last_name" => "Akande",
                "phone_number" => 8132402786,
                "email" => "akandeaaj@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Christopher",
                "last_name" => "Akinfenwa",
                "phone_number" => 7049546094,
                "email" => "taiwoakinfenwa2019@gmail.com",
                "gender" => "Male",
                "address" => "UI",
                "date_of_birth" => "10-Aug",
                "community" => "",
                "worker" => "Yes",
                "unit" => "Worship Team",
                "status" => ""
            ],
            [
                "first_name" => "Toluwalashe",
                "last_name" => "Akinola",
                "phone_number" => 8102810733,
                "email" => "akinolatoluwalashe48@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oluwadamilola",
                "last_name" => "Alabi",
                "phone_number" => "",
                "email" => "",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Marvel",
                "last_name" => "Angulu",
                "phone_number" => "",
                "email" => "angulumarvel@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Ajisafe",
                "last_name" => "Arewa",
                "phone_number" => 906406002,
                "email" => "Arewaoluwa60@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Jesunifesimi",
                "last_name" => "Ayedona",
                "phone_number" => 8121569780,
                "email" => "grace789nife@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Praise",
                "last_name" => "Ayoade",
                "phone_number" => 9070959365,
                "email" => "Bigpraise001@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Praise",
                "last_name" => "Ayoade",
                "phone_number" => "",
                "email" => "",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Taiwo",
                "last_name" => "Bajomo",
                "phone_number" => 7048578260,
                "email" => "rotimibajomo32@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Paul",
                "last_name" => "Bamibe",
                "phone_number" => 8137971612,
                "email" => "bamibepaul@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Erioluwa",
                "last_name" => "Bamibe",
                "phone_number" => 9039598060,
                "email" => "erioluwabamibe@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Esther",
                "last_name" => "Benson",
                "phone_number" => 9061848780,
                "email" => "bensone797@gmail.com",
                "gender" => "Female",
                "address" => "Sawmill, Old Ife road, Ibadan",
                "date_of_birth" => "01-Jan",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Honor-Jesus",
                "last_name" => "Bezaleel",
                "phone_number" => "",
                "email" => "",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Abigael",
                "last_name" => "Blessing",
                "phone_number" => 7087502990,
                "email" => "abigaelblessing2021@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Abiodun",
                "last_name" => "Chikodi",
                "phone_number" => 9153881831,
                "email" => "Akintayokemi626@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oluwatobiloba",
                "last_name" => "Dairo",
                "phone_number" => 8180203799,
                "email" => "gladysoluwatobi@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Agbaraoluwa",
                "last_name" => "David",
                "phone_number" => 7032512720,
                "email" => "davidagbaraoluwa19@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "Worship Team",
                "status" => ""
            ],
            [
                "first_name" => "Benjamin",
                "last_name" => "Ekinns",
                "phone_number" => 9122315574,
                "email" => "inihobongbenjamin@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Jessica",
                "last_name" => "Emmanuel",
                "phone_number" => 9022644851,
                "email" => "jessicaemmanuel039@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Ayomide",
                "last_name" => "Emmanuel",
                "phone_number" => 7069947801,
                "email" => "emmanayomide1@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Amudipe",
                "last_name" => "Esther",
                "phone_number" => 8147192513,
                "email" => "Xtarife3@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Comfort",
                "last_name" => "Fadiya",
                "phone_number" => 7031686396,
                "email" => "comfortfadiya@gmail.com",
                "gender" => "Female",
                "address" => "Bodija, Ibadan",
                "date_of_birth" => "23-Sep",
                "community" => "",
                "worker" => "Yes",
                "unit" => "Worship Team",
                "status" => ""
            ],
            [
                "first_name" => "Ayomide",
                "last_name" => "Fasasi",
                "phone_number" => "",
                "email" => "",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Salami",
                "last_name" => "Feyisara",
                "phone_number" => 8113045029,
                "email" => "feyisharahdolapo@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Olamide",
                "last_name" => "Gbadegesin",
                "phone_number" => 9027919322,
                "email" => "gbadeola2010@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Olasunkanmi",
                "last_name" => "Gbadegesin",
                "phone_number" => 9063474054,
                "email" => "olasunkanmi.gbadegesin@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oluwalayomi",
                "last_name" => "Gbadegesin",
                "phone_number" => 8104398529,
                "email" => "oluwalayomifunmilola@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Comfort",
                "last_name" => "Godwin",
                "phone_number" => 9127758876,
                "email" => "godwincomfort14@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Faith",
                "last_name" => "Igwe",
                "phone_number" => 9167129850,
                "email" => "patienceigwe.7facebook@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Chisom",
                "last_name" => "Igwe",
                "phone_number" => 8083176669,
                "email" => "Kimberlyigwe@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Blessing",
                "last_name" => "Iloduba",
                "phone_number" => 8135762874,
                "email" => "ogechi.chiqito@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oyindamola",
                "last_name" => "Ishola",
                "phone_number" => 7069293698,
                "email" => "isholaoyindamola93@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Olajide",
                "last_name" => "Israel",
                "phone_number" => 7048781604,
                "email" => "olajideisreal2000@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Adebayo",
                "last_name" => "Joseph",
                "phone_number" => 8101761075,
                "email" => "adebayophilipjoseph@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Funmilayo",
                "last_name" => "Joseph",
                "phone_number" => 7031005595,
                "email" => "Funmilayormodara@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Emmanuel",
                "last_name" => "King",
                "phone_number" => 7038644539,
                "email" => "Emmanuelolatayo54@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Tomike",
                "last_name" => "Kolajo",
                "phone_number" => 8106827158,
                "email" => "kolajoelizabeth@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Ademola Pelumi",
                "last_name" => "Lawal",
                "phone_number" => 8167257148,
                "email" => "pelumiademola260@gmail.com",
                "gender" => "Male",
                "address" => "Foye Street, Adegbayi",
                "date_of_birth" => "14-Jan",
                "community" => "",
                "worker" => "Yes",
                "unit" => "Worship Team",
                "status" => ""
            ],
            [
                "first_name" => "Morireoluwa",
                "last_name" => "Lawrence",
                "phone_number" => 9019963839,
                "email" => "morireoluwalawrence@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Layo",
                "last_name" => "Mi",
                "phone_number" => 8161245884,
                "email" => "empresslayomi@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Daniel",
                "last_name" => "Micah-Daniels",
                "phone_number" => 8134754954,
                "email" => "lekanm715@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Olajumoke",
                "last_name" => "Michael",
                "phone_number" => 8163071708,
                "email" => "michaelolajumoke98@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Kehinde",
                "last_name" => "Moronfolu",
                "phone_number" => 7037618943,
                "email" => "oluwatomisinsarah@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Kehinde",
                "last_name" => "Moronfolu",
                "phone_number" => 7037618943,
                "email" => "oluwatomisinsarah@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Adejumo",
                "last_name" => "Mosunmola",
                "phone_number" => 8102355043,
                "email" => "Mosunmlaadejumo50@mail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Sanmi-alao",
                "last_name" => "Moyosoreoluwa",
                "phone_number" => 8073505634,
                "email" => "tmoyosoreoluwa@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Yisau",
                "last_name" => "Mujidat oluwafunmilayo",
                "phone_number" => 8164263035,
                "email" => "Avow16@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Ike",
                "last_name" => "Niyi",
                "phone_number" => 8143500722,
                "email" => "Niyiike@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Jane",
                "last_name" => "Nwaiwu",
                "phone_number" => 9030553734,
                "email" => "jhanedhera@gmail.com",
                "gender" => "Female",
                "address" => "Agbowo, Ibadan",
                "date_of_birth" => "11-May",
                "community" => "",
                "worker" => "Yes",
                "unit" => "Worship Team",
                "status" => ""
            ],
            [
                "first_name" => "Oluwaremilekun",
                "last_name" => "Ogunnowo",
                "phone_number" => 8164338510,
                "email" => "ogunnowooluwaremilekun7@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oluwanishola",
                "last_name" => "Ogunnowo",
                "phone_number" => 8166041582,
                "email" => "oluwanisholaoluwalowo@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Timilehin",
                "last_name" => "Oguntuase",
                "phone_number" => 7037464638,
                "email" => "raphaelbts232@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Taiwo",
                "last_name" => "Ojeleye",
                "phone_number" => 9075816455,
                "email" => "Ojeleyetaiwo00@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Jane",
                "last_name" => "Ojewole",
                "phone_number" => 9034499599,
                "email" => "Ololadetaiwoj@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Tolani",
                "last_name" => "Ojo",
                "phone_number" => 8164100979,
                "email" => "ojotolanimercy2019@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Victor",
                "last_name" => "Okonkwo",
                "phone_number" => 9129138514,
                "email" => "Okonkwovictordgreat@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Opeyemi",
                "last_name" => "Okunola",
                "phone_number" => 8146412563,
                "email" => "opeyemiadebowale1759@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Israel",
                "last_name" => "Olajide",
                "phone_number" => 7048781604,
                "email" => "olajideisreal2000@gmail.com",
                "gender" => "Male",
                "address" => "Independence hall, UI",
                "date_of_birth" => "02-Jul",
                "community" => "",
                "worker" => "Yes",
                "unit" => "Worship Team",
                "status" => ""
            ],
            [
                "first_name" => "Bukola",
                "last_name" => "Olanase",
                "phone_number" => 7087033539,
                "email" => "oluwabukolaolanase@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Opeyemi",
                "last_name" => "Olanase",
                "phone_number" => 8108448464,
                "email" => "olanaseopeyemi069@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Isaiah",
                "last_name" => "Olaoye",
                "phone_number" => 8138867668,
                "email" => "blessingolarinoye1@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Inioluwa",
                "last_name" => "Olarinoye",
                "phone_number" => 8138867668,
                "email" => "blessingolarinoye1@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oluwaseun",
                "last_name" => "Olatunde",
                "phone_number" => 8062739882,
                "email" => "oluwaseunolatundeaj@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Favour",
                "last_name" => "Olatunji",
                "phone_number" => 9073877048,
                "email" => "favourolatunji1505@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Inioluwa",
                "last_name" => "Olatunji",
                "phone_number" => 8037316709,
                "email" => "olatunjiinioluwa2308@gamil.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Favour",
                "last_name" => "Olujimi",
                "phone_number" => 8167231700,
                "email" => "Olujinmifavoureniiyi@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Joseph",
                "last_name" => "Olusi",
                "phone_number" => 9023809732,
                "email" => "olusijoseph23@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oluwanishola",
                "last_name" => "Oluwalowo",
                "phone_number" => 8166041582,
                "email" => "oluwanisholaoluwalowo@gmail.com",
                "gender" => "Male",
                "address" => "16 Flats, Agbowo, Ibadan",
                "date_of_birth" => "09-May",
                "community" => "",
                "worker" => "Yes",
                "unit" => "Worship Team",
                "status" => ""
            ],
            [
                "first_name" => "ADELEKE",
                "last_name" => "OLUWATOMISIN",
                "phone_number" => 8142452114,
                "email" => "holuwartominsin@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oluwatoni",
                "last_name" => "Omotosho",
                "phone_number" => 8097478687,
                "email" => "loisyforlife@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oluwadara",
                "last_name" => "Onakomaiya",
                "phone_number" => 7084173610,
                "email" => "oluwadaraeyitayo@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oluwagbemisola",
                "last_name" => "Oni",
                "phone_number" => 9160851717,
                "email" => "Gbemisolaoni09@gmail.com",
                "gender" => "Female",
                "address" => "Akala Estate, Akobo, Ibadan",
                "date_of_birth" => "03-Sep",
                "community" => "",
                "worker" => "Yes",
                "unit" => "Worship Team",
                "status" => ""
            ],
            [
                "first_name" => "Olanase",
                "last_name" => "Opeyemi",
                "phone_number" => 8108448464,
                "email" => "olanaseopeyemi069@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oluwatobiloba",
                "last_name" => "Oyedokun",
                "phone_number" => 8037316709,
                "email" => "olatunjiinioluwa2308@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Anita",
                "last_name" => "Patrick",
                "phone_number" => 8142762104,
                "email" => "anitaeleguase@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oluwatoyin",
                "last_name" => "Peter",
                "phone_number" => 8146412563,
                "email" => "oluwatoyinfaith26@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Surprise",
                "last_name" => "Popoola",
                "phone_number" => 9038834820,
                "email" => "popesurprise@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Olamide",
                "last_name" => "Rolake",
                "phone_number" => 8142628163,
                "email" => "Olofinkoyamorolake@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Pelumi",
                "last_name" => "Samson",
                "phone_number" => 9030841037,
                "email" => "samsongold001@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Abiodun",
                "last_name" => "Samuel Oluyemi",
                "phone_number" => 8164650987,
                "email" => "abiodunsamyemi@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oluwapelumi",
                "last_name" => "Sodeinde",
                "phone_number" => 7076643023,
                "email" => "Pemzysodes@gmail",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Olalekan",
                "last_name" => "Sonubi",
                "phone_number" => 7052546083,
                "email" => "sonubilekansolomon@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Kofoworola Daphne",
                "last_name" => "Soyinka",
                "phone_number" => 9025637257,
                "email" => "daphnesoyinka7@gmail.com",
                "gender" => "Female",
                "address" => "Akala Estate, Akobo, Ibadan",
                "date_of_birth" => "14-Jul",
                "community" => "",
                "worker" => "Yes",
                "unit" => "Worship Team",
                "status" => ""
            ],
            [
                "first_name" => "Gospel",
                "last_name" => "Sunday",
                "phone_number" => 7044606099,
                "email" => "gospelojonugwasunday@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Jesulayomi",
                "last_name" => "Taiwo",
                "phone_number" => 8084074360,
                "email" => "taiwojesulayomi95@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Jesujoba",
                "last_name" => "Taiwo",
                "phone_number" => 7061225747,
                "email" => "jesujobataiwo@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Jesunitemi",
                "last_name" => "Taiwo",
                "phone_number" => 8063737737,
                "email" => "rhemataiwo@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Ayomikun",
                "last_name" => "Taiwo",
                "phone_number" => 8168259465,
                "email" => "ayomikun010@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Damilola",
                "last_name" => "Tayo",
                "phone_number" => 9068924237,
                "email" => "damilolamariam70@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Opayemi",
                "last_name" => "Teniola Victoria",
                "phone_number" => 8130409112,
                "email" => "Opayemiteniola@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Miracle",
                "last_name" => "Ugochukwu",
                "phone_number" => 8124716614,
                "email" => "miracleugochukwu216@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => "Distant due the NYSC"
            ],
            [
                "first_name" => "Oluwagbenga",
                "last_name" => "Victor",
                "phone_number" => 8107936667,
                "email" => "olabodevictor28@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Dorcas",
                "last_name" => "Toyin",
                "phone_number" => 7032146606,
                "email" => "",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "No",
                "unit" => "",
                "status" => ""
            ],
        ];

        $usersOriginal = [
            [
                "first_name" => "Admin",
                "last_name" => "admin",
                "phone_number" => "string",
                "email" => "string",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Admin",
                "last_name" => "admin",
                "phone_number" => 1503,
                "email" => "admin@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Abiodun",
                "last_name" => "Samuel Oluyemi",
                "phone_number" => 8164650987,
                "email" => "abiodunsamyemi@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Olasunkanmi",
                "last_name" => "Gbadegesin",
                "phone_number" => 9063474054,
                "email" => "olasunkanmi.gbadegesin@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Adeyemi",
                "last_name" => "Agoro",
                "phone_number" => 8148989175,
                "email" => "agoroadeyemi65@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Toluwalashe",
                "last_name" => "Akinola",
                "phone_number" => 8102810733,
                "email" => "akinolatoluwalashe48@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Amudipe",
                "last_name" => "Esther",
                "phone_number" => 8147192513,
                "email" => "Xtarife3@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Bukola",
                "last_name" => "Olanase",
                "phone_number" => 7087033539,
                "email" => "oluwabukolaolanase@gmail.com",
                "gender" => "Male",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Oyindamola",
                "last_name" => "Ishola",
                "phone_number" => 7069293698,
                "email" => "isholaoyindamola93@gmail.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
            [
                "first_name" => "Inioluwa",
                "last_name" => "Olatunji",
                "phone_number" => 8037316709,
                "email" => "olatunjiinioluwa2308@gamil.com",
                "gender" => "Female",
                "address" => "",
                "date_of_birth" => "",
                "community" => "",
                "worker" => "Yes",
                "unit" => "",
                "status" => ""
            ],
        ];

        foreach ($usersOriginal as $userData) {
            $user = \App\Models\User::create([
                'first_name' => $userData['first_name'],
                'last_name' => $userData['last_name'],
                'phone_number' => $userData['phone_number'],
                'email' => $userData['email'],
                'gender' => $userData['gender'],
                'address' => $userData['address'],
                'date_of_birth' => $userData['date_of_birth'],
                'community' => $userData['community'],
                'worker' => $userData['worker'],
                'status' => $userData['status'],
                'password' => bcrypt($userData['phone_number']),
            ]);
            // Assign roles
            if ($user->email === 'admin@gmail.com') {
                $user->assignRole([UserRole::ADMIN->value, UserRole::MEMBER->value]);
            } elseif ($user->email === 'abiodunsamyemi@gmail.com') {
                $user->assignRole([UserRole::LEADER->value, UserRole::MEMBER->value]);
            } elseif ($user->email === 'string') {
                $user->assignRole([UserRole::ADMIN->value, UserRole::MEMBER->value]);
            } else {
                $user->assignRole(UserRole::MEMBER->value);
            }
        }
    }
}
