<?php

namespace Database\Seeders;

use App\Enums\RoleEnum;
use App\Models\User;
use App\Services\UserRoleService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Schema;

class UserSeeder extends Seeder
{
    public function __construct(
        private readonly UserRoleService $service
    ) {
    }

    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        DB::table('users')->truncate();

                $users = [
            [
                'id' => '1',
                'first_name' => 'Admin',
                'last_name' => 'Admin',
                'email' => 'admin@gcccibadan.org',
                'phone_number' => '08164650987',
                'gender' => 'Male',
                'address' => null,
                'community' => null,
                'status' => null,
                'email_verified_at' => null,
                'password' => '',
                'remember_token' => null,
                'date_of_birth' => null,
                'date_of_visit' => null,
                'created_at' => '31-08-25 1:02',
                'updated_at' => '31-08-25 1:02',
            ],
            [
                'id' => '75',
                'first_name' => 'Opeyemi',
                'last_name' => 'Okunola',
                'email' => 'opeyemiadebowale1759@gmail.com',
                'phone_number' => '08146412563',
                'gender' => 'Male',
                'address' => null,
                'community' => null,
                'status' => null,
                'email_verified_at' => null,
                'password' => '$2y$12$xz7x3sqbZjimj5K6kRQx3.5zQclaQLJYLVbsFqCeQpwv139zSGK2S',
                'remember_token' => null,
                'date_of_birth' => null,
                'date_of_visit' => null,
                'created_at' => '31-08-25 1:02',
                'updated_at' => '31-08-25 1:02',
            ],
    [
        'id' => 3,
        'first_name' => "Oluwatobi",
        'last_name' => "Abiona",
        'email' => "Oluwatobiabiona2@gmail.com",
        'phone_number' => "08132432908",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:20",
        'updated_at' => "2025-08-31 01:02:20",
    ],
    [
        'id' => 4,
        'first_name' => "Rosemary",
        'last_name' => "Achebe",
        'email' => "rosemaryashebe@gmail.com",
        'phone_number' => "08133215849",
        'gender' => "Female",
        'address' => "Ore Oloruntofunmi hostel, Major Salawu, Agbowo",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "20-Jul",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:20",
        'updated_at' => "2025-08-31 01:02:20",
    ],
    [
        'id' => 5,
        'first_name' => "Peter",
        'last_name' => "Adeagbo",
        'email' => "adeagbooluwagboyegapeter95@gmail.com",
        'phone_number' => "08142658150",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:20",
        'updated_at' => "2025-08-31 01:02:20",
    ],
    [
        'id' => 6,
        'first_name' => "John",
        'last_name' => "Adeagbo",
        'email' => "adeagbojohnluj@gmail.com",
        'phone_number' => "09153835134",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:20",
        'updated_at' => "2025-08-31 01:02:20",
    ],
    [
        'id' => 7,
        'first_name' => "Ajibade",
        'last_name' => "Adedayo",
        'email' => "theewhy72@gmail.com",
        'phone_number' => "09068979739",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:20",
        'updated_at' => "2025-08-31 01:02:20",
    ],
    [
        'id' => 8,
        'first_name' => "Adeuyi",
        'last_name' => "Adejoke",
        'email' => "Adejokeadeuyi0@gmail.com",
        'phone_number' => "07032913692",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:21",
        'updated_at' => "2025-08-31 01:02:21",
    ],
    [
        'id' => 9,
        'first_name' => "James",
        'last_name' => "Adeleke",
        'email' => "adejames97@gmail.com",
        'phone_number' => "08080392216",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:21",
        'updated_at' => "2025-08-31 01:02:21",
    ],
    [
        'id' => 10,
        'first_name' => "Adebisi",
        'last_name' => "Ademusire",
        'email' => "aadebisijoe@gmail.com",
        'phone_number' => "07031123695",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:21",
        'updated_at' => "2025-08-31 01:02:21",
    ],
    [
        'id' => 11,
        'first_name' => "Yetunde",
        'last_name' => "Adeniyi",
        'email' => "ayowealth4real@gmail.com",
        'phone_number' => "09168373724",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:21",
        'updated_at' => "2025-08-31 01:02:21",
    ],
    [
        'id' => 12,
        'first_name' => "Victoria",
        'last_name' => "Adesoji",
        'email' => "Victoriaadesoji@gmail.com",
        'phone_number' => "08127925156",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:21",
        'updated_at' => "2025-08-31 01:02:21",
    ],
    [
        'id' => 13,
        'first_name' => "Oluwatimileyin",
        'last_name' => "Adewale",
        'email' => "adewaleoluwatimileyin2020@gmail.com",
        'phone_number' => "07061631763",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:22",
        'updated_at' => "2025-08-31 01:02:22",
    ],
    [
        'id' => 14,
        'first_name' => "Samuel",
        'last_name' => "Adeyemo",
        'email' => "adexpsalm2@gmail.com",
        'phone_number' => "08145996831",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:22",
        'updated_at' => "2025-08-31 01:02:22",
    ],
    [
        'id' => 15,
        'first_name' => "Adeyemi",
        'last_name' => "Agoro",
        'email' => "agoroadeyemi65@gmail.com",
        'phone_number' => "08148989175",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:22",
        'updated_at' => "2025-08-31 01:02:22",
    ],
    [
        'id' => 16,
        'first_name' => "Opeyemi",
        'last_name' => "Ajala",
        'email' => "eesuolaopeyemi7@gmail.com",
        'phone_number' => "08162000203",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:22",
        'updated_at' => "2025-08-31 01:02:22",
    ],
    [
        'id' => 17,
        'first_name' => "Oluwasegun",
        'last_name' => "Ajala",
        'email' => "james.ajala@yahoo.com",
        'phone_number' => "07065518839",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:22",
        'updated_at' => "2025-08-31 01:02:22",
    ],
    [
        'id' => 18,
        'first_name' => "Tolulope",
        'last_name' => "Ajikanle",
        'email' => "ajikanletajworth@gmail.com",
        'phone_number' => "07068727719",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:23",
        'updated_at' => "2025-08-31 01:02:23",
    ],
    [
        'id' => 19,
        'first_name' => "Abayomi",
        'last_name' => "Akande",
        'email' => "akandeaaj@gmail.com",
        'phone_number' => "08132402786",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:23",
        'updated_at' => "2025-08-31 01:02:23",
    ],
    [
        'id' => 20,
        'first_name' => "Christopher",
        'last_name' => "Akinfenwa",
        'email' => "taiwoakinfenwa2019@gmail.com",
        'phone_number' => "07049546094",
        'gender' => "Male",
        'address' => "UI",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "10-Aug",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:23",
        'updated_at' => "2025-08-31 01:02:23",
    ],
    [
        'id' => 21,
        'first_name' => "Toluwalashe",
        'last_name' => "Akinola",
        'email' => "akinolatoluwalashe48@gmail.com",
        'phone_number' => "08102810733",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:23",
        'updated_at' => "2025-08-31 01:02:23",
    ],
    [
        'id' => 22,
        'first_name' => "Oluwadamilola",
        'last_name' => "Alabi",
        'email' => "alabidamilola0507@gmail.com",
        'phone_number' => "08138236051",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:23",
        'updated_at' => "2025-08-31 01:02:23",
    ],
    [
        'id' => 23,
        'first_name' => "Marvel",
        'last_name' => "Angulu",
        'email' => "angulumarvel@gmail.com",
        'phone_number' => "08053388869",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:24",
        'updated_at' => "2025-08-31 01:02:24",
    ],
    [
        'id' => 25,
        'first_name' => "Jesunifesimi",
        'last_name' => "Ayedona",
        'email' => "grace789nife@gmail.com",
        'phone_number' => "08121569780",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:24",
        'updated_at' => "2025-08-31 01:02:24",
    ],
    [
        'id' => 26,
        'first_name' => "Praise",
        'last_name' => "Ayoade",
        'email' => "Bigpraise001@gmail.com",
        'phone_number' => "09070959365",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:24",
        'updated_at' => "2025-08-31 01:02:24",
    ],
    [
        'id' => 27,
        'first_name' => "Taiwo",
        'last_name' => "Bajomo",
        'email' => "rotimibajomo32@gmail.com",
        'phone_number' => "07048578260",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:24",
        'updated_at' => "2025-08-31 01:02:24",
    ],
    [
        'id' => 28,
        'first_name' => "Paul",
        'last_name' => "Bamibe",
        'email' => "bamibepaul@gmail.com",
        'phone_number' => "08137971612",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:25",
        'updated_at' => "2025-08-31 01:02:25",
    ],
    [
        'id' => 29,
        'first_name' => "Erioluwa",
        'last_name' => "Bamibe",
        'email' => "erioluwabamibe@gmail.com",
        'phone_number' => "09039598060",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:25",
        'updated_at' => "2025-08-31 01:02:25",
    ],
    [
        'id' => 30,
        'first_name' => "Esther",
        'last_name' => "Benson",
        'email' => "bensone797@gmail.com",
        'phone_number' => "09061848780",
        'gender' => "Female",
        'address' => "Sawmill, Old Ife road, Ibadan",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "01-Jan",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:25",
        'updated_at' => "2025-08-31 01:02:25",
    ],
    [
        'id' => 31,
        'first_name' => "Honor-Jesus",
        'last_name' => "Bezaleel",
        'email' => "bhonourjesus@gmail.com",
        'phone_number' => "09033344206",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:25",
        'updated_at' => "2025-08-31 01:02:25",
    ],
    [
        'id' => 32,
        'first_name' => "Abigael",
        'last_name' => "Blessing",
        'email' => "abigaelblessing2021@gmail.com",
        'phone_number' => "07087502990",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:25",
        'updated_at' => "2025-08-31 01:02:25",
    ],
    [
        'id' => 33,
        'first_name' => "Abiodun",
        'last_name' => "Chikodi",
        'email' => "Akintayokemi626@gmail.com",
        'phone_number' => "09153881831",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:26",
        'updated_at' => "2025-08-31 01:02:26",
    ],
    [
        'id' => 34,
        'first_name' => "Oluwatobiloba",
        'last_name' => "Dairo",
        'email' => "gladysoluwatobi@gmail.com",
        'phone_number' => "08180203799",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:26",
        'updated_at' => "2025-08-31 01:02:26",
    ],
    [
        'id' => 35,
        'first_name' => "Agbaraoluwa",
        'last_name' => "David",
        'email' => "davidagbaraoluwa19@gmail.com",
        'phone_number' => "07032512720",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:26",
        'updated_at' => "2025-08-31 01:02:26",
    ],
    [
        'id' => 36,
        'first_name' => "Benjamin",
        'last_name' => "Ekinns",
        'email' => "inihobongbenjamin@gmail.com",
        'phone_number' => "09122315574",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:26",
        'updated_at' => "2025-08-31 01:02:26",
    ],
    [
        'id' => 38,
        'first_name' => "Ayomide",
        'last_name' => "Emmanuel",
        'email' => "emmanayomide1@gmail.com",
        'phone_number' => "07069947801",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:27",
        'updated_at' => "2025-08-31 01:02:27",
    ],
    [
        'id' => 39,
        'first_name' => "Amudipe",
        'last_name' => "Esther",
        'email' => "Xtarife3@gmail.com",
        'phone_number' => "08147192513",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:27",
        'updated_at' => "2025-08-31 01:02:27",
    ],
    [
        'id' => 40,
        'first_name' => "Comfort",
        'last_name' => "Fadiya",
        'email' => "comfortfadiya@gmail.com",
        'phone_number' => "07031686396",
        'gender' => "Female",
        'address' => "Bodija, Ibadan",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "23-Sep",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:27",
        'updated_at' => "2025-08-31 01:02:27",
    ],
    [
        'id' => 41,
        'first_name' => "Ayomide",
        'last_name' => "Fasasi",
        'email' => "AyomideFasasi@gmail.com",
        'phone_number' => "AyomideFasasi",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:27",
        'updated_at' => "2025-08-31 01:02:27",
    ],
    [
        'id' => 42,
        'first_name' => "Salami",
        'last_name' => "Feyisara",
        'email' => "feyisharahdolapo@gmail.com",
        'phone_number' => "08113045029",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:27",
        'updated_at' => "2025-08-31 01:02:27",
    ],
    [
        'id' => 43,
        'first_name' => "Olamide",
        'last_name' => "Gbadegesin",
        'email' => "gbadeola2010@gmail.com",
        'phone_number' => "09027919322",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:28",
        'updated_at' => "2025-08-31 01:02:28",
    ],
    [
        'id' => 44,
        'first_name' => "Olasunkanmi",
        'last_name' => "Gbadegesin",
        'email' => "olasunkanmi.gbadegesin@gmail.com",
        'phone_number' => "09063474054",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:28",
        'updated_at' => "2025-08-31 01:02:28",
    ],
    [
        'id' => 45,
        'first_name' => "Oluwalayomi",
        'last_name' => "Gbadegesin",
        'email' => "oluwalayomifunmilola@gmail.com",
        'phone_number' => "08104398529",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:28",
        'updated_at' => "2025-08-31 01:02:28",
    ],
    [
        'id' => 46,
        'first_name' => "Comfort",
        'last_name' => "Godwin",
        'email' => "godwincomfort14@gmail.com",
        'phone_number' => "09127758876",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:28",
        'updated_at' => "2025-08-31 01:02:28",
    ],
    [
        'id' => 47,
        'first_name' => "Faith",
        'last_name' => "Igwe",
        'email' => "patienceigwe.7facebook@gmail.com",
        'phone_number' => "09167129850",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:28",
        'updated_at' => "2025-08-31 01:02:28",
    ],
    [
        'id' => 48,
        'first_name' => "Chisom",
        'last_name' => "Igwe",
        'email' => "Kimberlyigwe@gmail.com",
        'phone_number' => "08083176669",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:29",
        'updated_at' => "2025-08-31 01:02:29",
    ],
    [
        'id' => 49,
        'first_name' => "Blessing",
        'last_name' => "Iloduba",
        'email' => "ogechi.chiqito@gmail.com",
        'phone_number' => "08135762874",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:29",
        'updated_at' => "2025-08-31 01:02:29",
    ],
    [
        'id' => 50,
        'first_name' => "Oyindamola",
        'last_name' => "Ishola",
        'email' => "isholaoyindamola93@gmail.com",
        'phone_number' => "07069293698",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:29",
        'updated_at' => "2025-08-31 01:02:29",
    ],
    [
        'id' => 52,
        'first_name' => "Adebayo",
        'last_name' => "Joseph",
        'email' => "adebayophilipjoseph@gmail.com",
        'phone_number' => "08101761075",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:29",
        'updated_at' => "2025-08-31 01:02:29",
    ],
    [
        'id' => 53,
        'first_name' => "Funmilayo",
        'last_name' => "Joseph",
        'email' => "Funmilayormodara@gmail.com",
        'phone_number' => "07031005595",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:30",
        'updated_at' => "2025-08-31 01:02:30",
    ],
    [
        'id' => 54,
        'first_name' => "Emmanuel",
        'last_name' => "King",
        'email' => "Emmanuelolatayo54@gmail.com",
        'phone_number' => "07038644539",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:30",
        'updated_at' => "2025-08-31 01:02:30",
    ],
    [
        'id' => 55,
        'first_name' => "Tomike",
        'last_name' => "Kolajo",
        'email' => "kolajoelizabeth@gmail.com",
        'phone_number' => "08106827158",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:30",
        'updated_at' => "2025-08-31 01:02:30",
    ],
    [
        'id' => 56,
        'first_name' => "Ademola Pelumi",
        'last_name' => "Lawal",
        'email' => "pelumiademola260@gmail.com",
        'phone_number' => "08167257148",
        'gender' => "Male",
        'address' => "Foye Street, Adegbayi",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "14-Jan",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:30",
        'updated_at' => "2025-08-31 01:02:30",
    ],
    [
        'id' => 57,
        'first_name' => "Morireoluwa",
        'last_name' => "Lawrence",
        'email' => "morireoluwalawrence@gmail.com",
        'phone_number' => "09019963839",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:30",
        'updated_at' => "2025-08-31 01:02:30",
    ],
    [
        'id' => 58,
        'first_name' => "Layo",
        'last_name' => "Mi",
        'email' => "empresslayomi@gmail.com",
        'phone_number' => "08161245884",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:31",
        'updated_at' => "2025-08-31 01:02:31",
    ],
    [
        'id' => 59,
        'first_name' => "Daniel",
        'last_name' => "Micah-Daniels",
        'email' => "lekanm715@gmail.com",
        'phone_number' => "08134754954",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:31",
        'updated_at' => "2025-08-31 01:02:31",
    ],
    [
        'id' => 60,
        'first_name' => "Olajumoke",
        'last_name' => "Michael",
        'email' => "michaelolajumoke98@gmail.com",
        'phone_number' => "08163071708",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:31",
        'updated_at' => "2025-08-31 01:02:31",
    ],
    [
        'id' => 61,
        'first_name' => "Kehinde",
        'last_name' => "Moronfolu",
        'email' => "oluwatomisinsarah@gmail.com",
        'phone_number' => "07037618943",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:31",
        'updated_at' => "2025-08-31 01:02:31",
    ],
    [
        'id' => 63,
        'first_name' => "Adejumo",
        'last_name' => "Mosunmola",
        'email' => "Mosunmlaadejumo50@mail.com",
        'phone_number' => "08102355043",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:32",
        'updated_at' => "2025-08-31 01:02:32",
    ],
    [
        'id' => 64,
        'first_name' => "Sanmi-alao",
        'last_name' => "Moyosoreoluwa",
        'email' => "tmoyosoreoluwa@gmail.com",
        'phone_number' => "08073505634",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:32",
        'updated_at' => "2025-08-31 01:02:32",
    ],
    [
        'id' => 65,
        'first_name' => "Yisau",
        'last_name' => "Mujidat oluwafunmilayo",
        'email' => "Avow16@gmail.com",
        'phone_number' => "08164263035",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:32",
        'updated_at' => "2025-08-31 01:02:32",
    ],
    [
        'id' => 66,
        'first_name' => "Ike",
        'last_name' => "Niyi",
        'email' => "Niyiike@gmail.com",
        'phone_number' => "08143500722",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:32",
        'updated_at' => "2025-08-31 01:02:32",
    ],
    [
        'id' => 67,
        'first_name' => "Jane",
        'last_name' => "Nwaiwu",
        'email' => "jhanedhera@gmail.com",
        'phone_number' => "09030553734",
        'gender' => "Female",
        'address' => "Agbowo, Ibadan",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "11-May",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:32",
        'updated_at' => "2025-08-31 01:02:32",
    ],
    [
        'id' => 68,
        'first_name' => "Oluwaremilekun",
        'last_name' => "Ogunnowo",
        'email' => "ogunnowooluwaremilekun7@gmail.com",
        'phone_number' => "08164338510",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:33",
        'updated_at' => "2025-08-31 01:02:33",
    ],
    [
        'id' => 70,
        'first_name' => "Timilehin",
        'last_name' => "Oguntuase",
        'email' => "raphaelbts232@gmail.com",
        'phone_number' => "07037464638",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:33",
        'updated_at' => "2025-08-31 01:02:33",
    ],
    [
        'id' => 71,
        'first_name' => "Taiwo",
        'last_name' => "Ojeleye",
        'email' => "Ojeleyetaiwo00@gmail.com",
        'phone_number' => "09075816455",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:33",
        'updated_at' => "2025-08-31 01:02:33",
    ],
    [
        'id' => 72,
        'first_name' => "Jane",
        'last_name' => "Ojewole",
        'email' => "Ololadetaiwoj@gmail.com",
        'phone_number' => "09034499599",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:33",
        'updated_at' => "2025-08-31 01:02:33",
    ],
    [
        'id' => 73,
        'first_name' => "Tolani",
        'last_name' => "Ojo",
        'email' => "ojotolanimercy2019@gmail.com",
        'phone_number' => "08164100979",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:34",
        'updated_at' => "2025-08-31 01:02:34",
    ],
    [
        'id' => 74,
        'first_name' => "Victor",
        'last_name' => "Okonkwo",
        'email' => "Okonkwovictordgreat@gmail.com",
        'phone_number' => "09129138514",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:34",
        'updated_at' => "2025-08-31 01:02:34",
    ],
    [
        'id' => 76,
        'first_name' => "Israel",
        'last_name' => "Olajide",
        'email' => "olajideisreal2000@gmail.com",
        'phone_number' => "07048781604",
        'gender' => "Male",
        'address' => "Independence hall, UI",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "02-Jul",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:34",
        'updated_at' => "2025-08-31 01:02:34",
    ],
    [
        'id' => 78,
        'first_name' => "Opeyemi",
        'last_name' => "Olanase",
        'email' => "olanaseopeyemi069@gmail.com",
        'phone_number' => "08108448464",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:35",
        'updated_at' => "2025-08-31 01:02:35",
    ],
    [
        'id' => 79,
        'first_name' => "Isaiah",
        'last_name' => "Olaoye",
        'email' => "blessingolarinoye1@gmail.com",
        'phone_number' => "08138867668",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:35",
        'updated_at' => "2025-08-31 01:02:35",
    ],
    [
        'id' => 81,
        'first_name' => "Oluwaseun",
        'last_name' => "Olatunde",
        'email' => "oluwaseunolatundeaj@gmail.com",
        'phone_number' => "08062739882",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:35",
        'updated_at' => "2025-08-31 01:02:35",
    ],
    [
        'id' => 82,
        'first_name' => "Favour",
        'last_name' => "Olatunji",
        'email' => "favourolatunji1505@gmail.com",
        'phone_number' => "09073877048",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:35",
        'updated_at' => "2025-08-31 01:02:35",
    ],
    [
        'id' => 84,
        'first_name' => "Favour",
        'last_name' => "Olujimi",
        'email' => "Olujinmifavoureniiyi@gmail.com",
        'phone_number' => "08167231700",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:36",
        'updated_at' => "2025-08-31 01:02:36",
    ],
    [
        'id' => 85,
        'first_name' => "Joseph",
        'last_name' => "Olusi",
        'email' => "olusijoseph23@gmail.com",
        'phone_number' => "09023809732",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:36",
        'updated_at' => "2025-08-31 01:02:36",
    ],
    [
        'id' => 86,
        'first_name' => "Oluwanishola",
        'last_name' => "Oluwalowo",
        'email' => "oluwanisholaoluwalowo@gmail.com",
        'phone_number' => "08166041582",
        'gender' => "Male",
        'address' => "16 Flats, Agbowo, Ibadan",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "09-May",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:36",
        'updated_at' => "2025-08-31 01:02:36",
    ],
    [
        'id' => 87,
        'first_name' => "ADELEKE",
        'last_name' => "OLUWATOMISIN",
        'email' => "holuwartominsin@gmail.com",
        'phone_number' => "08142452114",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:36",
        'updated_at' => "2025-08-31 01:02:36",
    ],
    [
        'id' => 88,
        'first_name' => "Oluwatoni",
        'last_name' => "Omotosho",
        'email' => "loisyforlife@gmail.com",
        'phone_number' => "08097478687",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:37",
        'updated_at' => "2025-08-31 01:02:37",
    ],
    [
        'id' => 89,
        'first_name' => "Oluwadara",
        'last_name' => "Onakomaiya",
        'email' => "oluwadaraeyitayo@gmail.com",
        'phone_number' => "07084173610",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:37",
        'updated_at' => "2025-08-31 01:02:37",
    ],
    [
        'id' => 90,
        'first_name' => "Oluwagbemisola",
        'last_name' => "Oni",
        'email' => "Gbemisolaoni09@gmail.com",
        'phone_number' => "09160851717",
        'gender' => "Female",
        'address' => "Akala Estate, Akobo, Ibadan",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "03-Sep",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:37",
        'updated_at' => "2025-08-31 01:02:37",
    ],
    [
        'id' => 91,
        'first_name' => "Olanase",
        'last_name' => "Opeyemi",
        'email' => "olanaseopeyemi0693@gmail.com",
        'phone_number' => "08108448464",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:37",
        'updated_at' => "2025-08-31 01:02:37",
    ],
    [
        'id' => 93,
        'first_name' => "Anita",
        'last_name' => "Patrick",
        'email' => "anitaeleguase@gmail.com",
        'phone_number' => "08142762104",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:38",
        'updated_at' => "2025-08-31 01:02:38",
    ],
    [
        'id' => 95,
        'first_name' => "Surprise",
        'last_name' => "Popoola",
        'email' => "popesurprise@gmail.com",
        'phone_number' => "09038834820",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:38",
        'updated_at' => "2025-08-31 01:02:38",
    ],
    [
        'id' => 96,
        'first_name' => "Olamide",
        'last_name' => "Rolake",
        'email' => "Olofinkoyamorolake@gmail.com",
        'phone_number' => "08142628163",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:38",
        'updated_at' => "2025-08-31 01:02:38",
    ],
    [
        'id' => 97,
        'first_name' => "Pelumi",
        'last_name' => "Samson",
        'email' => "samsongold001@gmail.com",
        'phone_number' => "09030841037",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:38",
        'updated_at' => "2025-08-31 01:02:38",
    ],
    [
        'id' => 98,
        'first_name' => "Samuel",
        'last_name' => "Abiodun",
        'email' => "abiodunsamyemi@gmail.com",
        'phone_number' => "08164650987",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:39",
        'updated_at' => "2025-08-31 01:02:39",
    ],
    [
        'id' => 99,
        'first_name' => "Oluwapelumi",
        'last_name' => "Sodeinde",
        'email' => "Pemzysodes@gmail",
        'phone_number' => "07076643023",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:39",
        'updated_at' => "2025-08-31 01:02:39",
    ],
    [
        'id' => 100,
        'first_name' => "Olalekan",
        'last_name' => "Sonubi",
        'email' => "sonubilekansolomon@gmail.com",
        'phone_number' => "07052546083",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:39",
        'updated_at' => "2025-08-31 01:02:39",
    ],
    [
        'id' => 101,
        'first_name' => "Kofoworola Daphne",
        'last_name' => "Soyinka",
        'email' => "daphnesoyinka7@gmail.com",
        'phone_number' => "09025637257",
        'gender' => "Female",
        'address' => "Akala Estate, Akobo, Ibadan",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "14-Jul",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:39",
        'updated_at' => "2025-08-31 01:02:39",
    ],
    [
        'id' => 102,
        'first_name' => "Gospel",
        'last_name' => "Sunday",
        'email' => "gospelojonugwasunday@gmail.com",
        'phone_number' => "07044606099",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:39",
        'updated_at' => "2025-08-31 01:02:39",
    ],
    [
        'id' => 103,
        'first_name' => "Jesulayomi",
        'last_name' => "Taiwo",
        'email' => "taiwojesulayomi95@gmail.com",
        'phone_number' => "08084074360",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:40",
        'updated_at' => "2025-08-31 01:02:40",
    ],
    [
        'id' => 104,
        'first_name' => "Jesujoba",
        'last_name' => "Taiwo",
        'email' => "jesujobataiwo@gmail.com",
        'phone_number' => "07061225747",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:40",
        'updated_at' => "2025-08-31 01:02:40",
    ],
    [
        'id' => 105,
        'first_name' => "Jesunitemi",
        'last_name' => "Taiwo",
        'email' => "rhemataiwo@gmail.com",
        'phone_number' => "08063737737",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:40",
        'updated_at' => "2025-08-31 01:02:40",
    ],
    [
        'id' => 106,
        'first_name' => "Ayomikun",
        'last_name' => "Taiwo",
        'email' => "ayomikun010@gmail.com",
        'phone_number' => "08168259465",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:40",
        'updated_at' => "2025-08-31 01:02:40",
    ],
    [
        'id' => 107,
        'first_name' => "Damilola",
        'last_name' => "Tayo",
        'email' => "damilolamariam70@gmail.com",
        'phone_number' => "09068924237",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:40",
        'updated_at' => "2025-08-31 01:02:40",
    ],
    [
        'id' => 108,
        'first_name' => "Opayemi",
        'last_name' => "Teniola Victoria",
        'email' => "Opayemiteniola@gmail.com",
        'phone_number' => "08130409112",
        'gender' => "Female",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:41",
        'updated_at' => "2025-08-31 01:02:41",
    ],
    [
        'id' => 109,
        'first_name' => "Miracle",
        'last_name' => "Ugochukwu",
        'email' => "miracleugochukwu216@gmail.com",
        'phone_number' => "08124716614",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "Distant due the NYSC",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:41",
        'updated_at' => "2025-08-31 01:02:41",
    ],
    [
        'id' => 110,
        'first_name' => "Oluwagbenga",
        'last_name' => "Victor",
        'email' => "olabodevictor28@gmail.com",
        'phone_number' => "08107936667",
        'gender' => "Male",
        'address' => "",
        'community' => "",


                'status' => "",
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => "",
        'date_of_visit' => null,
        'created_at' => "2025-08-31 01:02:41",
        'updated_at' => "2025-08-31 01:02:41",
    ],
    [
        'id' => 113,
        'first_name' => "DORCAS",
        'last_name' => "toyin",
        'email' => "dorcasfakayode19@gmail.com",
        'phone_number' => "07032146606",
        'gender' => "Female",
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-08-31 12:57:15",
        'updated_at' => "2025-08-31 12:57:15",
    ],
    [
        'id' => 114,
        'first_name' => "Oluwatoyin Faith",
        'last_name' => "Peter",
        'email' => "oluwatoyinfaith26@gmail.com",
        'phone_number' => "08114857637",
        'gender' => "Female",
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-01 03:53:37",
        'updated_at' => "2025-09-01 03:53:37",
    ],
    [
        'id' => 115,
        'first_name' => "Victory",
        'last_name' => "Abalaka",
        'email' => "abalakassec@gmail.com",
        'phone_number' => "09037788489",
        'gender' => null,
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-01 05:03:48",
        'updated_at' => "2025-09-01 05:03:48",
    ],
    [
        'id' => 116,
        'first_name' => "Oluwagbemiga",
        'last_name' => "Flourish",
        'email' => "flourisholuwagbemiga2019@gmail.com",
        'phone_number' => "07038575845",
        'gender' => null,
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-01 05:03:48",
        'updated_at' => "2025-09-01 05:03:48",
    ],
    [
        'id' => 117,
        'first_name' => "Success",
        'last_name' => "Udu",
        'email' => "udusuccess18@gmail.com",
        'phone_number' => "07054947265",
        'gender' => null,
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-01 05:03:49",
        'updated_at' => "2025-09-01 05:03:49",
    ],
    [
        'id' => 118,
        'first_name' => "Oluwatobiloba",
        'last_name' => "Bello",
        'email' => "bellotobiloba40@gmail.com",
        'phone_number' => "08128479329",
        'gender' => null,
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-01 05:03:49",
        'updated_at' => "2025-09-01 05:03:49",
    ],
    [
        'id' => 119,
        'first_name' => "Susan",
        'last_name' => "Uweribeno",
        'email' => "susanayobami3@gmail.com",
        'phone_number' => "09121339005",
        'gender' => null,
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-01 05:03:49",
        'updated_at' => "2025-09-01 05:03:49",
    ],
    [
        'id' => 120,
        'first_name' => "Isaiah",
        'last_name' => "Olaoye",
        'email' => "olaisaiah54@gmail.com",
        'phone_number' => "08057661190",
        'gender' => null,
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-01 05:03:49",
        'updated_at' => "2025-09-01 05:03:49",
    ],
    [
        'id' => 121,
        'first_name' => "Goodness",
        'last_name' => "Udofia",
        'email' => "goodnesseffiong1811@gmail.com",
        'phone_number' => "08102113246",
        'gender' => null,
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-01 05:03:49",
        'updated_at' => "2025-09-01 05:03:49",
    ],
    [
        'id' => 122,
        'first_name' => "Kemi",
        'last_name' => "Kemi",
        'email' => "osakuadeoluwakemisola@gmail.com",
        'phone_number' => "09051388493",
        'gender' => null,
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-01 05:03:50",
        'updated_at' => "2025-09-01 05:03:50",
    ],
    [
        'id' => 123,
        'first_name' => "Gift",
        'last_name' => "Akpala",
        'email' => "akpalagift24@gmail.com",
        'phone_number' => "08064776696",
        'gender' => null,
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-01 05:03:50",
        'updated_at' => "2025-09-01 05:03:50",
    ],
    [
        'id' => 124,
        'first_name' => "Bukola",
        'last_name' => "Olanase",
        'email' => "Bukolaolanase1000@gmail.com",
        'phone_number' => "07017965065",
        'gender' => null,
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-01 05:03:50",
        'updated_at' => "2025-09-01 05:03:50",
    ],
    [
        'id' => 126,
        'first_name' => "Temitayo",
        'last_name' => "ojo",
        'email' => "tayot1556@gmail.com",
        'phone_number' => "07047344329",
        'gender' => "Male",
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-10 04:58:50",
        'updated_at' => "2025-09-10 04:58:50",
    ],
    [
        'id' => 127,
        'first_name' => "victoria",
        'last_name' => "oluwapelumi",
        'email' => "victoriaoluwapelumi6@mail.com",
        'phone_number' => "07043029108",
        'gender' => "Female",
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-10 05:16:43",
        'updated_at' => "2025-09-10 05:16:43",
    ],
    [
        'id' => 128,
        'first_name' => "Arewa",
        'last_name' => "Ajisafe",
        'email' => "arewaoluwa60@gmail.com",
        'phone_number' => "09064060072",
        'gender' => "Female",
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-22 22:10:44",
        'updated_at' => "2025-09-22 22:10:44",
    ],
    [
        'id' => 129,
        'first_name' => "Oluwatobiloba",
        'last_name' => "Oyedokun",
        'email' => "oyedokunoluwatobiloba@gmail.com",
        'phone_number' => "0807395670",
        'gender' => "Female",
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-22 22:14:35",
        'updated_at' => "2025-09-22 22:14:35",
    ],
    [
        'id' => 130,
        'first_name' => "Esther",
        'last_name' => "Bolaji Ikeoluwa",
        'email' => "BolajiIkeoluwa5@gmail.com",
        'phone_number' => "09025153468",
        'gender' => "Female",
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-22 22:20:07",
        'updated_at' => "2025-09-22 22:20:07",
    ],
    [
        'id' => 131,
        'first_name' => "opeyemi",
        'last_name' => "balogun",
        'email' => "Ibkbalogun18@gmail.com",
        'phone_number' => "09164789369",
        'gender' => "Female",
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-09-28 08:03:28",
        'updated_at' => "2025-09-28 08:03:28",
    ],
    [
        'id' => 132,
        'first_name' => "John",
        'last_name' => "Omemu",
        'email' => "omemuoyinlayefa@gmail.com",
        'phone_number' => "08021106089",
        'gender' => "Male",
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-10-21 09:54:04",
        'updated_at' => "2025-10-21 09:54:04",
    ],
    [
        'id' => 133,
        'first_name' => "Jessica",
        'last_name' => "Emmanuel",
        'email' => "jessicaemmanuel039@gmail.com",
        'phone_number' => "09022644851",
        'gender' => "Female",
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-10-21 09:59:54",
        'updated_at' => "2025-10-21 09:59:54",
    ],
    [
        'id' => 134,
        'first_name' => "Inioluwa",
        'last_name' => "Ayodele",
        'email' => "theayodeleinioluwa@gmail.com",
        'phone_number' => "09058883720",
        'gender' => "Female",
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-10-21 10:01:24",
        'updated_at' => "2025-10-21 10:01:24",
    ],
    [
        'id' => 135,
        'first_name' => "Inioluwa",
        'last_name' => "Olatunji",
        'email' => "olatunjiinioluwa2308@gmail.com",
        'phone_number' => "08037316709",
        'gender' => "Female",
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-10-21 12:57:13",
        'updated_at' => "2025-10-21 12:57:13",
    ],
    [
        'id' => 138,
        'first_name' => "oluwagbenga Victor",
        'last_name' => "Olabode",
        'email' => "olabodevictor285@gmail.com",
        'phone_number' => "08107936667",
        'gender' => "Male",
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-10-27 02:10:45",
        'updated_at' => "2025-10-27 02:10:45",
    ],
    [
        'id' => 139,
        'first_name' => "Obodo",
        'last_name' => "Enu",
        'email' => "enuobodo@gmail.com",
        'phone_number' => "09036637353",
        'gender' => "Male",
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-10-27 02:11:29",
        'updated_at' => "2025-10-27 02:11:29",
    ],
    [
        'id' => 140,
        'first_name' => "Ore-ofe",
        'last_name' => "Sanni",
        'email' => "ohrexs@gmail.com",
        'phone_number' => "07086465020",
        'gender' => "Female",
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-10-27 02:33:06",
        'updated_at' => "2025-10-27 02:33:06",
    ],
    [
        'id' => 141,
        'first_name' => "Ojewole",
        'last_name' => "Oluwaseni",
        'email' => "Ojewoleseni@yahoo.com",
        'phone_number' => "08164870049",
        'gender' => null,
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-10-27 02:34:45",
        'updated_at' => "2025-10-27 02:34:45",
    ],
    [
        'id' => 142,
        'first_name' => "Precious",
        'last_name' => "Ejire",
        'email' => "pejire911@gmail.com",
        'phone_number' => "07055621269",
        'gender' => null,
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-10-27 02:38:01",
        'updated_at' => "2025-10-27 02:38:01",
    ],
    [
        'id' => 143,
        'first_name' => "Phoebe",
        'last_name' => "Itodo",
        'email' => "phoebeuyo833@gmail.com",
        'phone_number' => "08123845290",
        'gender' => null,
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-10-27 02:42:49",
        'updated_at' => "2025-10-27 02:42:49",
    ],
    [
        'id' => 144,
        'first_name' => "Precious",
        'last_name' => "Ajayi",
        'email' => "preciousayomide147@gmail.com",
        'phone_number' => "09131623617",
        'gender' => null,
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-10-27 02:42:50",
        'updated_at' => "2025-10-27 02:42:50",
    ],
    [
        'id' => 145,
        'first_name' => "Elizabeth",
        'last_name' => "Bassey",
        'email' => "princessbasseye@gmail.com",
        'phone_number' => "08139711398",
        'gender' => null,
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-10-27 02:42:50",
        'updated_at' => "2025-10-27 02:42:50",
    ],
    [
        'id' => 146,
        'first_name' => "Testimony",
        'last_name' => "Tanimowo",
        'email' => "Tanimowotestimony@gmail.comm",
        'phone_number' => "08135562645",
        'gender' => null,
        'address' => null,
        'community' => null,


                'status' => null,
        'email_verified_at' => null,
        'remember_token' => null,
        'date_of_birth' => null,
        'date_of_visit' => null,
        'created_at' => "2025-10-27 02:42:50",
        'updated_at' => "2025-10-27 02:42:50",
    ],
];

        foreach ($users as $userData) {
            $userData['password'] = Hash::make($userData['phone_number']);
            $userData['created_at'] = now();
            $userData['updated_at'] = now();
            $userData['status'] = 'active';
            $userData['date_of_visit'] = null;
            $userData['date_of_birth'] = null;

            $user = User::create($userData);
            if ($userData['email'] == 'admin@gcccibadan.org'  || $userData['email'] == 'Opeyemiadebowale1759@gmail.com' || $userData['email'] == 'abiodunsamyemi@gmail.com') {
                $this->service->assignUserRoles($user, [
                    RoleEnum::ADMIN->value,
                    RoleEnum::LEADER->value,
                    RoleEnum::MEMBER->value,
                ]);
            } else{
                 $this->service->assignUserRoles($user, [
                    RoleEnum::MEMBER->value,
                ]);
            }
        }
        //  'email' => "ajikanletajworth@gmail.com",
        // 'phone_number' => "07068727719",
        // $user = User::create([
        //     'first_name' => 'Admin',
        //     'last_name' => 'admin',
        //     'email' => 'admin@gcccibadan.org',
        //     'phone_number' => '08164650987',
        //     'gender' => 'Male',
        //     'password' => Hash::make('password')
        // ]);
        // $user2 = User::create([
        //     'id' => 18,
        //     'first_name' => 'Admin 2',
        //     'last_name' => 'admin 2',
        //     "email" => "user@example.com",
        //     'phone_number' => '08164650987',
        //     'gender' => 'Male',
        //     'password' => Hash::make('string')
        // ]);

        // $this->service->assignUserRoles($user, [
        //     RoleEnum::ADMIN->value,
        //     RoleEnum::LEADER->value,
        //     RoleEnum::MEMBER->value,
        // ]);
        // $this->service->assignUserRoles($user2, [
        //     RoleEnum::ADMIN->value,
        //     RoleEnum::LEADER->value,
        //     RoleEnum::MEMBER->value,
        // ]);
        Schema::enableForeignKeyConstraints();
    }
}
